### ISSUE TITLE
combine single letters to words

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#104]
Issue by @punkys, posted at AsTeRICS, moved to AsTeRICS Grid

Hey, I am really new to github, I hope I use it the right way..

I want to create a keyboard with single letters in AsTeRICS as a own grid. The letters should then be combined to words. Finally the words should be read out like words, not like single letters. I couldn't get it done yet.
For the purpose to create a keyboard I also need to configurate an elemente as "space", to devide single words. I think this isn't possible atm.
I would be really grateful for Your help.

Thanks & kind regards
Leo

**Comment by klues** [comment]
Hi @punkys,
thanks for your issue.
It's perfectly possible to create own keyboards where single characters can be put together to words. In the standard gridset open "keyboard" at the start page or  at "More" you can find alternative keyboard layouts at the bottom:
https://i.imgur.com/xFllwLK.png
https://i.imgur.com/6SLXZ9M.png

There are 2 Videos on Youtube, a [video about collection elements](https://www.youtube.com/watch?v=X6YrWJW2ZoM&list=PL0UXHkT03dGrIHldlEKR0ZWfNMkShuTNz&index=21) and another [video about prediction elements](https://www.youtube.com/watch?v=t0FWZcM9TMg&list=PL0UXHkT03dGrIHldlEKR0ZWfNMkShuTNz&index=22) which hopefully should give you enough information on how to create a completely new keyboard layout from scratch, if you don't want to use the existing ones.

**Comment by punkys** [comment]
Hey @klues
thanks alot!
The youtube playlist is perfect to learn more about AsTeRICS.

**Comment by punkys** [comment]
I somehow deleted the default settings and had a total blank AsTeRICS.
I made a new user and now I can work with the default configuration and just make the changes I need there.
I was a little overwhelmed, when I had the blank program and started to build some grids together.
This way it's much easier :)

**Comment by klues** [comment]
Prefect. You can also go to "Manage Grids -> More -> Reset to default configuration" to reset everything for the current user, see https://i.imgur.com/BT6EiwV.png

I'll close this issue just to indicate that your initial issue is resolved. But feel free to open other issues or to add more comments to this issue.
