### ISSUE TITLE
Accessibility Drop Down menu "Eingabeoptionen"

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#13]
When trying to open a menu entry of "Eingabeoptionen" using the keyboard, the entry cannot be selected and opened. 

How to reproduce:
1. Press tab to get to  button "Eingabeoptionen"
2. Press Space (the menu opens)
3. Press 'cursor down' (menu entry is selected)
4. Press Space (nothing happens)
5. Press Enter (the dialog opens and closes immediately)

![image](https://user-images.githubusercontent.com/4621810/66109380-cef4a100-e5c4-11e9-9199-24e7505f29dd.png)

## Solution
Make menu entry listening for Space key press?

**Comment by klues** [comment]
Fixed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2019-11-06-08.21/+0100
Still select menu entry with `Enter`.
