### ISSUE TITLE
Edit Grid button changes to ```Back``

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#15]
When pressing the ```Edit Grid``` button to edit a grid the button jumps to the left side and is called ```Back```.

## Solution
What about using a toggle button?

```Editing On```: --> when pressed looks like pressed
```Èditing Off```: --> when pressed, looks like unpressed

similar to the ```Lock``` button

**Comment by klues** [comment]
what do you think about this:
* in normal mode: http://prntscr.com/pwsasc - german: http://prntscr.com/pwsc1i
* in edit mode: http://prntscr.com/pwsb8c - german: http://prntscr.com/pwsc6g

I'm not sure about "Fertig" in the german version, but "Bearbeiten beenden" seems too long.

mobile:
* in normal mode: http://prntscr.com/pwsbpo
* in edit mode: http://prntscr.com/pwsbk4

**Comment by deinhofer** [comment]
> what do you think about this:
> 
>     * in normal mode: http://prntscr.com/pwsasc - german: http://prntscr.com/pwsc1i
> 
>     * in edit mode: http://prntscr.com/pwsb8c - german: http://prntscr.com/pwsc6g
> 
> 
> I'm not sure about "Fertig" in the german version, but "Bearbeiten beenden" seems too long.
> 
> mobile:
> 
>     * in normal mode: http://prntscr.com/pwsbpo
> 
>     * in edit mode: http://prntscr.com/pwsbk4

I like the moodle approach:

![image](https://user-images.githubusercontent.com/4621810/68845431-b56a6d00-06cb-11ea-861d-02f72db03884.png)
![image](https://user-images.githubusercontent.com/4621810/68845477-c3b88900-06cb-11ea-905c-bb44368ccbfe.png)

But I would shorten it to ```Bearbeiten ein``` <-> ```Bearbeiten aus```


In english: ```Editing on``` <-> ```Editing off```

The color coding is not necessary, I think.

**Comment by klues** [comment]
This is what the moodle approach looks in mobile mode: http://prntscr.com/pwsvyi 😉 
I also need a mobile version and mobile/desktop should use the same icons. I think the Off-icon is not very intuitive in the mobile view...

**Comment by deinhofer** [comment]
In mobile mode I would only use the Icon. What If you creat a new Icon and combine the pencil with the off-symbol? Or cross out the edit Icon?

**Comment by klues** [comment]
font-awesome does allow to stack icons, but the combination doesn't really looks great: http://prntscr.com/pww0pu

new attempt:
* desktop: http://prntscr.com/pwwb5x -> http://prntscr.com/pwwbyj
* mobile: https://prnt.sc/pwwcja -> http://prntscr.com/pwwcx8

I think the eye symbol could be used, it's also already used in manage grids view.

**Comment by deinhofer** [comment]
much better :-)

You could also use a switch icon https://www.flaticon.com/free-icon/switch_214326 
to represent the switching between editing and view mode.

But I also like the eye symbol. Looks good and would be consistent to the manage grids page.

**Comment by klues** [comment]
Yeah, I'll stick with the eye symbol. Thanks for your feedback!

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2019-11-19-16.18%2F%2B0100
