### ISSUE TITLE
Opensymbols search works but selected image does not appear in element using Chrome, Edge, Opera - But Firefox is OK

### ISSUE THREAD

**Issue by jamjolu** [asterics/AsTeRICS-Grid#153]
Tested in Chrome, Edge, Opera:
The ARASAAC search works fine. The image selected appears in the element.
However, the Opensymbols.org search works, but when you select a desired symbol, it does not appear in the element.

In Firefox the Opensymbols.org image search and image assignment to an element works fine.

**Comment by jamjolu** [comment]
I just noticed that although symbols found through Opensymbols.org don't show up in elements themselves, they do show up in the collection element once you select that element - in Google Chrome.

**Comment by klues** [comment]
Thanks for reporting the issue, I think I've fixed it. Please test on https://grid.asterics.eu/latest/ if everything is working there.
I've also changed that now the last used search provider is saved and automatically selected for the next time.

**Comment by klues** [comment]
closed by https://github.com/asterics/AsTeRICS-Grid/releases
