### ISSUE TITLE
Use Service Workers instead of AppCache

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#16]
Offline capabilities are currently implemented using [AppCache](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache). However this is an deprecated technology and it should be replaced by [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API).

Maybe interesting: https://github.com/HenrikJoreteg/appcache-serviceworker-generator

**Comment by klues** [comment]
Implemented with https://github.com/asterics/AsTeRICS-Grid/commit/fd14a227c09c871e994e38a4038137bd5f37e09f and other commits on the same day. Still needs to be tested on test environment.

Should work as follows:
* opening AsTeRICS Grid installs a Service Worker which sets up routes for all needed files to be cached using [Workbox](https://developers.google.com/web/tools/workbox)
* on Service Worker install event all needed files are precached, see [serviceWorker.js#L12](https://github.com/asterics/AsTeRICS-Grid/blob/master/serviceWorker.js#L12)
* the list of files to pre-cache is can be regenerated using [getServiceWorkerCachePaths.js](https://github.com/asterics/AsTeRICS-Grid/blob/master/scripts/getServiceWorkerCachePaths.js). Call it with `node getServiceWorkerCachePaths.js` and copy the contents of [serviceWorkerPaths.txt](https://github.com/asterics/AsTeRICS-Grid/blob/master/scripts/serviceWorkerPaths.txt) to [serviceWorker.js#L10](https://github.com/asterics/AsTeRICS-Grid/blob/master/serviceWorker.js#L10)
* The Service Worker is registered in [mainScript.js#L54](https://github.com/asterics/AsTeRICS-Grid/blob/master/src/js/mainScript.js#L54)
* Logic in [mainScript.js#L70-90](https://github.com/asterics/AsTeRICS-Grid/blob/master/src/js/mainScript.js#L70) automatically searches for Service Worker Updates every 15 Minutes. If a new Service Worker is found, it is installed and a Tooltip is shown in the application. The user is using the new version of AsTeRICS Grid, if he clicks on "Update now" in the tooltip or at the latest after re-opening AsTeRICS Grid the next time.

**Comment by sabicalija** [comment]
I'd like to test this feature. How can I build and run it locally? Thanks!

**Comment by klues** [comment]
It's already online at https://grid.asterics.eu/latest/
To run it locally:
1. clone the repo
2. run `yarn install` (npm doesn't work because of special dependency options I need)
3. run `yarn run start` or `npm run start`
4. open `localhost:9095`

Would be great if you can test it and submit feedback if you encounter any problems. Main functionality is offline capability of the whole app. Additionally you could test auto-update of the app/serviceworker by running the application and then change something (e.g. a log message) in https://github.com/asterics/AsTeRICS-Grid/blob/master/serviceWorker.js. Then wait 15 Minutes without reloading of the app and the new version of ServiceWorker/App should be loaded automatically in the background with an update message in the UI.

**Comment by klues** [comment]
One thing I forgot: at https://github.com/asterics/AsTeRICS-Grid/blob/master/src/js/mainScript.js#L55 you have to add `&& false` or similar to skip skipping of installing ServiceWorker ;)

**Comment by sabicalija** [comment]
I've just run the app at https://grid.asterics.eu/latest/. The service worker was installed successfully.

![image](https://user-images.githubusercontent.com/13609768/91535430-6e283280-e913-11ea-95b9-4fceb687058c.png)

Running AsTeRICS Grid offline works as well.

![image](https://user-images.githubusercontent.com/13609768/91535593-acbded00-e913-11ea-926e-e632887c350e.png)



I'll now run it locally and try to change stuff. What happens when there are new changes? Do I get informed about the updates or do I have to acknowledge them?

I've tried to build the app with `yarn build` yesterday, but I didn't know where the app was or how to deploy (locally). :grin: Thanks for the instructions.

**Comment by sabicalija** [comment]
The installation worked as well. :+1:

![image](https://user-images.githubusercontent.com/13609768/91536544-260a0f80-e915-11ea-8ae0-0f9d2171840e.png)


But maybe you should keep the `start_url` as  `https://grid.asterics.eu/lastest` as long as the service worker is only deployed there. It should match the location (URL) from where it is installed for stability reasons. Not sure how safe/stable using the location "." is. But it seems to work for me. It's using `https://grid.asterics.eu/lastest` - even if `https://grid.asterics.eu` is displayed in the "native" os application variant.

![image](https://user-images.githubusercontent.com/13609768/91536554-2acec380-e915-11ea-850a-f30144a07b6a.png)

![image](https://user-images.githubusercontent.com/13609768/91536596-3de19380-e915-11ea-87cf-33a99e969e63.png)

**Comment by sabicalija** [comment]
I've started it locally, but the service worker seems not to be installed.
![image](https://user-images.githubusercontent.com/13609768/91539802-2e187e00-e91a-11ea-920b-c8b275f28c1b.png)

Do you think it might be because of the unsecured localhost (using only http)? I've opened `0.0.0.0:9095` and `localhost:9095`, whereby the latter does not display any info about "not secure" connections. I think the service worker installation should work for `localhost` even without https.

Here is the log from the terminal. Am I using the current version or a legacy variant?
![image](https://user-images.githubusercontent.com/13609768/91539811-32449b80-e91a-11ea-92f6-f832bb73cbbc.png)

Oh. I just saw "Not installing Service Worker because on development environment". I've tried to start it with `NODE_ENV=production` but it resulted in the same log message.

**Comment by klues** [comment]
Thanks for testing!

> One thing I forgot: at https://github.com/asterics/AsTeRICS-Grid/blob/master/src/js/mainScript.js#L55 you have to add `&& false` or similar to skip skipping of installing ServiceWorker ;)

this is the reason for not installing the service worker locally ;)
I could also enable it by some flag on starting, but I currently don't know how to get information about a node flag in a javascript source.

> But maybe you should keep the start_url as https://grid.asterics.eu/lastest

I think it should be correct, according to https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url a relative `start_url` is relative to the location of the web manifest. So for `/latest` it should be resolved to `https://grid.asterics.eu/lastest/app/` because that's the location of the manifest. So the most correct value probably would be `../` but also `.` works, because in `/app` there is a `index.html` that's redirecting to `../`.

**Comment by klues** [comment]
> Here is the log from the terminal. Am I using the current version or a legacy variant?

You are using the current version. Once I had the current version (= bundle with non-transpiled ES6 syntax) and the legacy version (= bundle with transpiled ES6 syntax) and I included it this way in `index.html`:
```
<script src="app/build_legacy/asterics-grid.bundle.js"></script>
<script type="module" src="app/build/asterics-grid.bundle.js"></script>
```
The idea is to run ES6 syntax code in Browsers that support it, which maybe results in better performance, see https://philipwalton.com/articles/deploying-es2015-code-in-production-today/
However, loading the script with `type=module` in Firefox in combination with AppCache didn't work, so I'm currently simply using the "legacy" (transpiled) version everywhere.
Good that you asked -> with moving to ServiceWorker I maybe could go back to this strategy ;)

**Comment by klues** [comment]
closed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2020-09-10-15.30%2F%2B0200
