### ISSUE TITLE
Block/Unblock Zoom/Move webpage

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#163]
An option that allows the block/unblock zoom/move capabilities of the web navigators. We attach an iPad example of the issue.
[Video](https://app.box.com/s/plc3bp5nm4kql5e52clem127ieqfsmyd)

**Comment by klues** [comment]
I've prevented zoom in general and navigation in locked mode.
Note that preventing zoom is against WCAG guidlines, so it's a tradeoff between limiting accessibility for users with low vision and preventing users from being confused by accidential zooming. Maybe a solution would be to only disable zoom in locked mode - however I'm not sure if it's worth the effort.

Please test https://grid.asterics.eu/latest/ if it's working correctly now.

**Comment by arasaac-dga** [comment]
​We have tested in "latest", and, in general, work fine in Edge, Chrome and Safari. In Opera seems not work. We consider that users with low vision that use screen readers are not potentially users of locked mode. So, we consider that, by now, the best it's disable zoom and navigation globally in locked mode as you propose. We consider that it's not necessary at the moment develop a more personalized ​solution.

**Comment by klues** [comment]
OK, until now I didn't implement it like this, but now it's like I've proposed that zoom is only deactivated in locked mode. Please test again on "latest" and then I'll do the main release. For me it seems that deactivating the zoom only works for touch-zoom with 2 fingers on touchscreen devices, but zooming on desktop with the mouse is still possible.

**Comment by arasaac-dga** [comment]
Yes, the main problem is with touch screens. So, for us, it's ok this solution. It seems to work as expected (except for Opera like yesterday). So, you can update in main realease when you can. Thanks.

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-10-21-12.14/+0200
