### ISSUE TITLE
the accumulated phrase don't show the pictos on appropriate size

### ISSUE THREAD

**Issue by JulenAutismoAraba** [asterics/AsTeRICS-Grid#164]
Hello, i have one user that use Asterics on an iPad mini 2 with 12.5.6 iOs. When he clicks on a pictogram, it is displayed either very small or very large.
He is using Safari.
I add some images

**Screenshots**
![imagen](https://user-images.githubusercontent.com/115158873/195092022-f411a55a-0b4a-41f5-8da8-838846bfc67a.png)
![imagen](https://user-images.githubusercontent.com/115158873/195092062-e9040b35-24d8-46c2-9813-0dedfd2bb886.png)
![imagen](https://user-images.githubusercontent.com/115158873/195092096-cd516814-2685-4cba-9d7f-1773215bd02c.png)

**Desktop (please complete the following information):**

 - OS: iOs
 - Browser Safari
 - Version 12.5.6

**Smartphone (please complete the following information):**
 - Device: iPad mini 2 
 - OS: iOs 
 - Browser Safari
 - Version 12.5.6

**Comment by arasaac-dga** [comment]
Here is possible to see a [video](https://app.box.com/s/hk7artjoq7k44ctlho6u8l10ieoxhw1b) with similar problems in Edge with an Ipad Air 2 tablet : 
![IMG_20221014_122430](https://user-images.githubusercontent.com/82500056/195830595-3ffb8f80-506f-40d6-9034-89a56baec14d.jpg)

**Comment by klues** [comment]
Thanks, I think I've found the reason and solution using an older apple device on https://www.browserstack.com/
Please test https://grid.asterics.eu/latest/ and tell me if it fixes the problem

**Comment by klues** [comment]
should be fixed with release https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-10-17-14.19%2F%2B0200
