### ISSUE TITLE
"Convert uppercase keyboard letters to lowercase" in accumulated phrase options must be desactivated when reset

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#166]
**Describe the bug**
When the Global Grid is reset, the "Convert uppercase keyboard letters to lowercase" option is activated. By default must deactivated. 

**To Reproduce**
1. Go to Manage Grids
2. Click on "Reset Global Grid"
3. Edit Global Grid
4. Edit Accumulated phrase
5. You see "Convert uppercase keyboard letters to lowercase" option activated.

**Comment by klues** [comment]
Please test https://grid.asterics.eu/latest/ if it's working correctly now.

**Comment by klues** [comment]
Please keep the issues open until I'm closing them on releasing the main version.

**Comment by arasaac-dga** [comment]
Ok. Understand.

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-10-21-12.14/+0200
