### ISSUE TITLE
Uppercase predictive text

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#167]
Possibility to transform to uppercase predictive text when it is suggested and when it accumulates in the sentence.

**Comment by arasaac-dga** [comment]
Yes, It sounds logic. So, for us, link to this configuration. Thanks

**Comment by klues** [comment]
Please test at https://grid.asterics.eu/latest/

**Comment by arasaac-dga** [comment]
Work as expected. Thanks

**Comment by klues** [comment]
Released to main version with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-11-10-10.40%2F%2B0100
