### ISSUE TITLE
More options in scanning input "advanced settings"

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#170]
Add an option to "Read out active element" of the active cell before selecting it and another option to allow the scanning method cell by cell only (beginning by the first row).

**Comment by klues** [comment]
Cell-by-cell with reading out active cell is already possible, it's called "Sequential input" and is a separate input method. There it also shows the option "read out active element" in the advanced options. For scanning I don't think it makes that much sense, since it's unclear what to read out when multiple elements are highlighted.

**Comment by klues** [comment]
OK, then we could add the feature for automatically going to the next element after some time to "Sequential input". Scanning as implemented now is in general selecting groups of elements until reaching the final element, not single elements.

However we can also think about acoustic feedback for the group-based scanning, but it then should be something like beep tones for automatically going to the next group and a different beep tone for coming back to the first group. At the level of highlighting single elements the labels could be read out.

**Comment by arasaac-dga** [comment]
We have tested and it seems to work fine. Anyway, you can remain open this issue although you implement in main version because we have some users than are testing it and we are wainting their comments.

**Comment by klues** [comment]
I've just improved the texts for reading out the active elements (not published yet) in order to also hear something if the element doesn't have a label. Please translate the new translations to spanish on crowdin, then I can do the main release.

**Comment by arasaac-dga** [comment]
Ok. Translated in Crowdin. Do the msin release when you can. Thanks.

**Comment by klues** [comment]
released current state to main with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-10-25-16.09%2F%2B0200

**Comment by klues** [comment]
Changed slightly with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-11-10-10.40%2F%2B0100
Acoustic feedback settings were relocated, see https://github.com/asterics/AsTeRICS-Grid/issues/169#issuecomment-1305777377
