### ISSUE TITLE
Cell without label text (empty) but with "Speak custom text" is not accumulated

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#172]
Sometimes for low level users it's not neccesary to set a label text for cell but it's neccesary to set a custom text. In this cases (no label text) but with action "Speak custom text", the pisctogram is not added to the accumulated phrase.

**Comment by klues** [comment]
It's now possible to collect elements with image only. For speaking the accumulated phrase should then the custom text be spoken (not implemented yet)?
Please test at https://grid.asterics.eu/latest/

**Comment by arasaac-dga** [comment]
Yes it's neccesary that custom text be spoken when the phrase is readed. Thanks

**Comment by klues** [comment]
If no label existing, now custom speak text is used.
Released to main version with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-11-10-10.40%2F%2B0100
