### ISSUE TITLE
When revisiting a grid with a YouTube Player, Player fails.

### ISSUE THREAD

**Issue by jamjolu** [asterics/AsTeRICS-Grid#174]
When revisiting a grid with a YouTube Player, Player fails.
If I got o a grid with a YouTube player, it works fine on the first visit. But, if I navigate away, and then return, the player fails. 
Tested in Google Chrome v 106.0.5249.119
Tested in Firefox v 106.0.1
![yt_second_visit](https://user-images.githubusercontent.com/24657766/197815036-4233d14e-1a34-4421-8c47-625d730c144c.png)
![yt_first_visit_More](https://user-images.githubusercontent.com/24657766/197815120-86cac11f-dbdc-4e6d-8bae-8ae790007732.png)
![yt_first_visit](https://user-images.githubusercontent.com/24657766/197815172-dfffbba8-a877-450d-90ae-44ae910ef9f8.png)

**Comment by klues** [comment]
Thanks for reporting, should be fixed at the beta/testing version. Please test at https://grid.asterics.eu/latest/

**Comment by klues** [comment]
Released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-11-10-10.40%2F%2B0100
