### ISSUE TITLE
Hidden cells are printed in PDF

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#175]
Hidden cells in grids are printed in PDF. We understand hidden cells must not be printed either in PDF.

**Comment by klues** [comment]
Please test at https://grid.asterics.eu/latest/

**Comment by arasaac-dga** [comment]
Great!!! Works fine.

**Comment by klues** [comment]
Released to main version with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-11-10-10.40%2F%2B0100
