### ISSUE TITLE
Orphaned custom text

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#177]
**Describe the bug**
Custom text is spoken, when clicking onto the cell, but when editing the custom text, the custom text field is empty.

**To Reproduce**
1. Import .grd file ([orphane-custom-text.zip](https://github.com/asterics/AsTeRICS-Grid/files/9882117/orphane-custom-text.zip))
2. Click on cell "mein lieblingsessen ist lachs mit reis": It should be spoken in Russian
3. Edit cell and try to edit the custom text
4. The custom text field "Text to speak" is empty

**Expected behavior**
Spoken text should be in field "text to speak"

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.04
 - Browser chrome 105

**Comment by klues** [comment]
Thanks for filing the issue.
In the configuration you've uploaded the text to speak is stored with lang code `eu` which is Basque, I don't know how this has happened:
![grafik](https://user-images.githubusercontent.com/2537025/200813396-6e65a8ce-9bcd-4d9d-bc15-41e097e34fc9.png)

However I've now fixed it that always the text of the currently set speak language is shown/available for edit, see linked commit.

**Comment by klues** [comment]
Please test at https://grid.asterics.eu/latest/

**Comment by klues** [comment]
Released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-11-10-10.40%2F%2B0100

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-01-17-14.54%2F%2B0100

**Comment by deinhofer** [comment]
Thank you!
Regarding editing of the custom text, this looks good now. :-)

But when I set several custom texts in several languages, e.g. 
  * Spanish: "Me gusta Wiener Schnitzel"
  * Deutsch: "Ich liebe Wiener Schitzel"

and add a cell to change the language from Spanish to German, still the spanish custom text is spoken out loud.

It would also be helpful to have an indicator on the start page or even in the grid (e.g. language flag or similar) to see which language is currently active.

**Comment by klues** [comment]
I've just tested it and for me it seems to work:
* started with empty config in inkognito tab
* first element with custom texts in two languages, as you commented
* 2 other elements to switch to Spanish / German

For Spanish, the spanish text is spoken with a spanish voice and for German the german text with german voice. See this backup:
[default-user_2023-01-19_14-26_asterics-grid-full-backup.zip](https://github.com/asterics/AsTeRICS-Grid/files/10457100/default-user_2023-01-19_14-26_asterics-grid-full-backup.zip)
