### ISSUE TITLE
Backups files renamed (added ".txt" as new extension) when are downloaded in some navigators and operative systems

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#178]
After some comments of users that cannot import backup files, we have discovered that in some navigators and some operative systems rename the grd files adding the extension ".txt" when they are downloaded. In many cases,people don't detect the rename because the file managers don't show the file extensions. So, they don't see that they have been renamed adding ".txt". 

At the moment, we have detected the problem in:

+ Android 10-11 with Google Chrome, Opera and Edge when the file is stored in internal memory (if you save the file in external sd, for example, with Chrome is not renamed). 

+ Ipad-Safari. Here is more problematic because the filemager doesn't show the file extensions. Only if you see the file properties if possible to see that it has been renamed.

**Comment by ChrisVeigl** [comment]
is the resulting file extension then ".grd.txt" ?
could we maybe just allow that ".txt" extension additionally to ".grd" ?

**Comment by arasaac-dga** [comment]
Yes, the result is "filename.grd.txt". Windows and other Android versions don't rename the files.

**Comment by arasaac-dga** [comment]
When a ".grd" file name renamed with txt is imported, it is confused for the final user because the process of import begins (percentage) but at the end, nothing happens and the user comes back to the initial screen (when the restore backup option is used).

**Comment by klues** [comment]
It's now possible to also select `.txt` files for importing a backup and they also should be correctly imported. If the `.txt` doesn't contain valid data, an error message is shown.
Please test at https://grid.asterics.eu/latest/

**Comment by arasaac-dga** [comment]
We have tried to import a rename valid backup file and it works fine. It's imported. But we have created a txt with an aleatory text inside and we  haven't seen the message of error.

**Comment by klues** [comment]
OK, fixed this, now the error message should be shown on all invalid `.txt` files.
Released to main version with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-11-10-10.40%2F%2B0100
