### ISSUE TITLE
Easier method for adding new grid element navigating to other/new grid

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#193]
Currently these steps are necessary in order to create a new grid element navigating to a new grid:
1. go to "Manage grids" and create a new grid
2. go to edit mode of another grid
3. create new grid element there
4. edit the new grid element, add an action "navigate to other grid" and select the newly created grid

I think there should be an easier way to do it:
1. Go to edit mode of a grid
2. Add new element with action "navigate to other grid"
3. Possibility to directly create a new grid there like this: 
![grafik](https://user-images.githubusercontent.com/2537025/203745761-4274166a-b5e2-4203-a252-87c92b38cb76.png)

**Comment by arasaac-dga** [comment]
Yes. It's a good feature to make the link grid process. Additionally, to this feature consider adding an option in the right click menu of a cell to "Navigate to a grid" that allows to select a created grid and add automatically the action to the cell. It's a complementary option to improve usability of this action.

**Comment by klues** [comment]
OK, yes, I even like your suggestion better. Right click on a grid element -> "Navigate to grid" would open a separate popup where the user can select an existing grid or create a new one to link it to the grid element. I think then the new option in "navigate to other grid" action wouldn't be needed.

**Comment by arasaac-dga** [comment]
Ok, if you complete the right click option adding the possibility to create the new grid too (and link the new one or other created), we consider that the other option, as you comment, it's not neccesary. So, go on with the right click option and discard the other one. Thanks.

**Comment by klues** [comment]
closed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-12-15-15.15%2F%2B0100
