### ISSUE TITLE
Text written with keyboard don't apply "Text transform" configuration option

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#201]
Having a keyboard made in uppercase, when you configure "Text transform" to lowercase in configuration, the text accumulated in phrase is shown in uppercase (although in general configuration of accumulated phrase you check transform to lowercase too). The keyboard shows the keys in lowercase but they are accumulated in uppercase. In other cases show the first letter in lowercase and the others in uppercase. If the keyboard is in lowercase, it produces some error but showing the text in lowercase in accumulated phrases.

**Comment by klues** [comment]
please test again at https://grid.asterics.eu/latest/

**Comment by arasaac-dga** [comment]
Works as expected. Thanks.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-01-17-14.54%2F%2B0100
