### ISSUE TITLE
Change automatically "Home Grid" in "Home Cell" of Global Grid when change it in "Select Home Grid for creating global Grid"

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#202]
Users comment that it is confused with the "Select Home Grid for creating global Grid" option because they think that when they change the selected grid, it is automatically changed in the home button in Global Grid. Although "Restore Gobal Grid" change the home button link, it would  be necessary that it is an independent action that doesn't implies to "Restore Global Grid". It must be an automatic change (like others in configuration).

**Comment by klues** [comment]
Added possibility to select home grid at the bottom of "Manage grids":
![grafik](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/f3f3b1fa-43ba-4639-9966-cbe31dc6d59f)

In navigation action now it's possible to select `navigate to home grid`:
![grafik](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/15447998-fc9b-4bab-8d59-e6e3470eb4b4)

The "home" button of the default global grid now has this option activated.

Released to [grid.asterics.eu/latest/](https://grid.asterics.eu/latest/) - please test.

**Comment by arasaac-dga** [comment]
We have tried all the new options related to Home Grid and work as expected. Great addition!!! Thanks. The only suggestion we have (if it's possible) would be to advise the users that have not activated the "Navigate to Home Grid" option in the Home button (inside the Global Grid), that they have to activate it if they want that the Home Grid selected in the list works. Indeed it would be great if in the advice message you can activate it without the need to edit Global Grid and Home Button. If we don't advise it could be confusing for people because they will change the Home Grid selecting one in the list but not take effect because the don't have active the new "Navigate to home grid" option in "Navigate to other grid" action.

**Comment by klues** [comment]
Now the "home" element in global grid is automatically updated, if the home grid is changed, please test.

see https://github.com/asterics/AsTeRICS-Grid/commit/538b3118eaebfae1d47e4c3b6e0a570ceb17f463

**Comment by arasaac-dga** [comment]
Yes, it works as expected. Great. We have seen that although the "Navigate to other grid" action has not selected the sub-action "navigate to home grid" the system set it when you change the home grid selection in Manage Grid. So, it's more transparente for final user. Great!!!

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-01-03-12.25%2F%2B0100
