### ISSUE TITLE
Grid bug on board - Newly created cells are so small

### ISSUE THREAD

**Issue by anlolli92** [asterics/AsTeRICS-Grid#203]
After some playing around with a board, it seems the underlaying grid becomes very small, and any new cell created gets that size.
![Captura de pantalla 2022-12-01 a las 8 44 31](https://user-images.githubusercontent.com/116308201/204997170-61f7d11e-49ca-42ea-8995-95e0136a332d.png)
![Captura de pantalla 2022-12-01 a las 8 45 24](https://user-images.githubusercontent.com/116308201/204997208-f62bfa2e-9039-4ec5-b428-806f8ac45284.png)

Nevertheless, in the board settings, the size is stablished as 5x8 cells.

**Comment by klues** [comment]
It looks like it's the result of another bug. The grid in your screenshot has too many columns which is a result of aligning the global grid (first row) with the other grid in normal view mode. This shouldn't be done and seen in edit mode, but somehow it is.

Is this the only grid where this happened or is it the same with other grids?
If it's only this grid, please just try to make all items smaller and afterwards click on this option: 
![grafik](https://user-images.githubusercontent.com/2537025/205065289-aa972195-e1bd-4c2f-b1a4-d75046824df0.png)

If it happens regularly also with other grids, we'll try to find the cause.

**Comment by klues** [comment]
I'm closing this since there was no response anymore. Feel free to reopen.

**Comment by klues** [comment]
There's now a new option in grid edit mode "Normalize grid layout" which can help in similar situations, see https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-12-19-15.36%2F%2B0100
