### ISSUE TITLE
Recorded sounds do not play on IOS

### ISSUE THREAD

**Issue by rgabo74** [asterics/AsTeRICS-Grid#214]
I recorded sounds on Desktop both in Chrome and Safari and they are playing fine in the desktop browsers.
I am having the same user on mobile (IOS), which is synchronizing the grids, but the recorded sounds do not play there properly.
The behavior is exactly the same in Safari and Chome:
If I click on an element with synthesised sound, it is playing always fine. When I click on an element with recorded sound, it plays once, but never again. After this if I click on a synthesised one, it is playing again and reseting the problem. The first click on recorded sound playing once.

**Comment by klues** [comment]
Thanks for reporting. Unfortunately I don't have an iOS device to test and reproduce. I've just tried to test using https://www.browserstack.com/ - however sound output is quite unreliable in general on their devices.

Is it the same if you're playing a recording that was recorded by the iOS device?

**Comment by rgabo74** [comment]
I now involved a chrome browser on windows to the tests. The result is the following:

- it does not matter what device or browser is recording. Recording works in all tested devices.
- The playback always crashig on IOS browser (in Safari, Chrome, Opera the same way) after the first recorded sound playback.
- The playback is correct both in Safari/MacOS and Chrome/Windows with any recording device.

Additionally I observed, that the playback button on the recorded sound UI module also got stuck in play state (showing stop recrange sign endlessly)

**Comment by klues** [comment]
I've used https://www.browserstack.com/ to test and now managed to find a fix to get playback of recordings working on an iPad with Chrome/Safari/iOS 15. Before the fix audio playback didn't work at all on this device.

I've released this version to https://grid.asterics.eu/latest/ so please test there on your device.

**Comment by rgabo74** [comment]
Hey, Klaus, thanks for fixing! Nice job, playback is working fine now.

**Comment by klues** [comment]
Great, released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-12-23-13.15%2F%2B0100
