### ISSUE TITLE
Element selection in edit mode by tapping on mobile's touch screen is unreliable

### ISSUE THREAD

**Issue by rgabo74** [asterics/AsTeRICS-Grid#217]
When I am trying to edit a grid on mobile (Safari and Chrome in IOS) the green focus indicator does not appear most of the time. I need to tap several times (10-ish)  in order to make an element selected.

**Comment by klues** [comment]
Thanks for reporting, should be fixed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-12-23-13.15%2F%2B0100

Please confirm.
