### ISSUE TITLE
Tap and drag action on IOS making it difficult for child to activate an element

### ISSUE THREAD

**Issue by rgabo74** [asterics/AsTeRICS-Grid#219]
Both in Full screen and locked mode when kid is not tapping on the screen but touching and dragging a bit, the whole page moves down instead of executing the actions for touched card. This making it very hard for my kid to take actions.

Maybe a similar capability is needed for touch actions, what is available for the mouse "Directly select element on pressing mouse button (not waiting for complete click)"

Not sure if the dragging of the full page can be prevented... It would be possible to deal with it under lock mode as long as the dragging would execute the element actions.

**Comment by klues** [comment]
I've tried this:
1. If you enable the setting `Directly select element on pressing mouse button (not waiting for complete click)` it's not only listening to `mousedown` but also to `touchstart`. So it should directly select the symbol when start touching the screen.
2. I've disabled this long-touch menu for images: 
![grafik](https://user-images.githubusercontent.com/2537025/209645571-e7debc85-f3b6-4fee-8ea5-4c9ead629886.png)

Please test at https://grid.asterics.eu/latest/

**Comment by rgabo74** [comment]
Hi,
1, I can confirm this works, but it is having a side effect. In case of navigation action programmed for the card, a longer touch, it resulting quick drilling down the grid hierarchy to the bottom. So I would not let this change to the release. Kids need to learn touch and release.
2, Disabling the long touch menu is great, but something still happens in the browser which making the image zoom to the size of the element and at the same time the touch event is not happening. Can the long touch be set for the same action as touch but without this zoom magic? 
Thanks,Gabor

Sent from Yahoo Mail for iPhone


On Tuesday, December 27, 2022, 10:47 AM, Benjamin Klaus ***@***.***> wrote:




I've tried this:
   
   - If you enable the setting Directly select element on pressing mouse button (not waiting for complete click) it's not only listening to mousedown but also to touchstart. So it should directly select the symbol when start touching the screen.
   - I've disabled this long-touch menu for images:   


Please test at https://grid.asterics.eu/latest/

**Comment by klues** [comment]
I've added some code to ensure that additional selections are only done after a `touchend` event, so after the finger was lifted from the screen.

Please test at https://grid.asterics.eu/latest/

**Comment by rgabo74** [comment]
The improvement works well, when I click on an empty element or element label.
If there is an image on the element and I touch the image, then the bahavior is the previous, navigatng down to the botom of the hierarchy. Also a long touch event is making the image zoomed.

Gabor

Sent from Yahoo Mail for iPhone


On Tuesday, December 27, 2022, 5:15 PM, Benjamin Klaus ***@***.***> wrote:




I've added some code to ensure that additional selections are only done after a touchend event, so after the finger was lifted from the screen.

Please test at https://grid.asterics.eu/latest/

**Comment by klues** [comment]
This is really not an easy one since it seems it also includes this browser bug: https://bugs.chromium.org/p/chromium/issues/detail?id=464579

I think I've found a solution but I cannot test it, since the iOS devices from https://www.browserstack.com/ create `touchend` events event if I keep pressing the mouse button.

So please test again on https://grid.asterics.eu/latest/
As far as I could test the zooming on long touch should also be prevented.

**Comment by rgabo74** [comment]
Hi Benjamin,
The touch and navigation on the elements is working as expected now, well done on working this out without a device. :)  
There is one side effect on disabling the page scrolling which is not easy to describe...- On IOS on Chrome and Safari the page seems to be vertically sized to the size of the browser window- The size of the viewport is somewhat lower because the browser renders a toolbar/addressbar on the bottom or top of the screen.- If I am zooming in to the lower part of the page, then zoom out, then the upper Grid menu gets out of the viewport and become invisible and can't be scrolled down easily.- Why and how did I zoom? On an edit modal I zoomed in to see a small text and then scrolled down to the bottom of the page to hit OK, then zoomed out.- When I zoomed out to the bottom of the page, it is not easy to scroll up to see the menu bar as the scrolling and long touch is disabled. The only small area where you can scroll the page is the lower, grey part of the side menubar and even there it can only be done by two finger scrolling. This will trick the regular users, they won't be able to get the upper Grid menu back.- The problem does not happen if the browser toolbar is hidden by the user, since the browser window and viewport size are identical this case. It does not either happen when Grid is installed with an application shortcut. 
My webdev knowledge is limited to suggest what could be the easy fix for this...- Is there maybe an event for 100% zoom out on which you can scroll up to the top of the page to make the menu visible?- Or can you detect the height of the viewport and scale the page for that?


Sent from Yahoo Mail for iPhone


On Wednesday, December 28, 2022, 4:00 PM, Benjamin Klaus ***@***.***> wrote:




This is really not an easy one since it seems it also includes this browser bug: https://bugs.chromium.org/p/chromium/issues/detail?id=464579

I think I've found a solution but I cannot test it, since the iOS devices from https://www.browserstack.com/ create touchend events event if I keep pressing the mouse button.

So please test again on https://grid.asterics.eu/latest/
As far as I could test the zooming on long touch should also be prevented.

**Comment by klues** [comment]
Great that the navigation is now working as expected! 🥳 

Regarding zooming and viewport size: for me on Android initially something at the bottom is missing and after swiping up a little bit the top addressbar is hidden and the full size of the app can be seen:
![image](https://user-images.githubusercontent.com/2537025/209925254-b68e603f-a644-4710-a9e1-9136948c12b4.png)

For me zooming is working everywhere, only in locked mode it's disabled, see https://github.com/asterics/AsTeRICS-Grid/issues/163

Did zoom work for you as expected before I did the changes for this issue? If it's independent, please open a new issue for it, maybe also with screenshots. I think for fixing it, I'll definitely will have to use a real device for testing.

**Comment by rgabo74** [comment]
Hi Klaus,
I checked the zoom problem and it appear to be the same in /latest build and the production build. So I think we are good to go prof with these changes. It was also tested with my kid in the past days and was working all right.
I will open a separate issue about the zoom. Will do some more testing and screenshots, screen recordings. 
Gábor
    On Thursday, December 29, 2022 at 09:38:15 AM GMT+1, Benjamin Klaus ***@***.***> wrote:  
 
 


Great that the navigation is now working as expected! 🥳
 
Regarding zooming and viewport size: for me on Android initially something at the bottom is missing and after swiping up a little bit the top addressbar is hidden and the full size of the app can be seen:


For me zooming is working everywhere, only in locked mode it's disabled, see #163

Did zoom work for you as expected before I did the changes for this issue? If it's independent, please open a new issue for it, maybe also with screenshots. I think for fixing it, I'll definitely will have to use a real device for testing.

**Comment by klues** [comment]
Thanks for testing and confirming! Then I'll release this to main the main version and yes, please open a new issue for the zoom problem.

**Comment by klues** [comment]
Released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-01-05-10.26%2F%2B0100
As said, please open a new issue for the zoom problem.
