### ISSUE TITLE
Implement Sound Actions

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#22]
In addition to the current actions that can be defined for a grid element it should be possible to define "sound actions".

In the Modal: Edit grid -> right click on grid element -> Actions
there should be the possibility to add a "sound action".

**Requirements:**
* possibility to upload an existing sound file
* possibility to directly record a sound sample using the microphone of the device and the browser microphone API.
* size of uploaded sound samples should be limited, e.g. max. 1MB or max. 15 seconds.

**Comment by klues** [comment]
While implementing this, I'm wondering if the distinction between the "collect modes" of a collect element really makes sense and is needed:
![grafik](https://user-images.githubusercontent.com/2537025/202452660-a8b2ae80-5cf3-4549-9734-7accebf9a2d0.png)

I'm thinking about removing it and just always automatically decide how to collect elements. If the elements contain pictograms, I'm using mixed mode with pictograms and text and if no element contains a pictogram, I'm using the mode where only text is collected (e.g. for a keyboard).
@arasaac-dga: do you also think we could remove this option or do you think we need it?

**Comment by klues** [comment]
@arasaac-dga: please test the latest version at https://grid.asterics.eu/latest/

Changes:
* it's now possible to add an action "Play recorded audio" and record audio for it using the microphone of the device, see https://i.imgur.com/DpsdaQl.png
* In the collect element:
   * I've added the possibility to define to speak the collected text separately or continously, see: https://i.imgur.com/T7jHI29.png
   * For continous mode all collected text is spoken at once using TTS
   * For separate mode all collected elements are spoken separately, highlighting the currently spoken element, like before. For elements with recorded audio action, the audio is played instead of speaking the text with TTS.

I would suggest to change the default global grid to:
* click on collect element -> speak separately and keep content
* click on play button -> speak continously and clear

Please test everything related to collect element since I had to change quite much within the code.

**Comment by arasaac-dga** [comment]
> @arasaac-dga: please test the latest version at https://grid.asterics.eu/latest/
> 
> Changes:
> 
> * it's now possible to add an action "Play recorded audio" and record audio for it using the microphone of the device, see https://i.imgur.com/DpsdaQl.png
> * In the collect element:
>   
>   * I've added the possibility to define to speak the collected text separately or continously, see: https://i.imgur.com/T7jHI29.png
>   * For continous mode all collected text is spoken at once using TTS
>   * For separate mode all collected elements are spoken separately, highlighting the currently spoken element, like before. For elements with recorded audio action, the audio is played instead of speaking the text with TTS.
> 
> I would suggest to change the default global grid to:
> 
> * click on collect element -> speak separately and keep content
> * click on play button -> speak continously and clear
> 
> Please test everything related to collect element since I had to change quite much within the code.

We have tested the new record feature and it works as expected. Great work!!! As a suggestion to improve usability, we propose that you add a message below the record/play option in which warn that the record audio is only played (listen) in "speak separately" in collect element actions. 

Related to the suggest of change the default global grid our proposal is simple:

- click on collect element -> speak continuously
- click on play button -> speak continuously

Why? Because "speak continuously" is the most natural option in language and the preferred one and without "clear" because many people have commented that prefer to use the trash button to delete. So, we consider that "speak  continuously" as action in both elements is the best. 

Can you change the "global grid" configuration automatically for all the predefined communicators and for the default global grid configuration (reset button)? Thanks.

**Comment by klues** [comment]
Thanks for your feedback, I'll implement it as you've commented.
I've just also added correct handling and warning message if the user rejects to allow microphone usage.

An open question for me:
* What if an element contains both actions "speak label" and "play recorded audio"? I think both should be played after each other not simultaneously like now?! Or should "speak label" should be omitted, if "play recorded audio" is existing?

**Comment by klues** [comment]
I've just released to https://grid.asterics.eu/latest/ :
* don't play "speak label" if "play recorded audio" is existing on selecting an element
* added an info message if speak mode for collect element is "continuously" with direct possibility to change it: https://i.imgur.com/GKKte3m.png (don't know what the best description is here - do you have a better suggestion?)
* For the default global grid, the text of the collect element is now spoken continuously -> I still have to change it for the default configurations, but for "start with empty config" or "reset global grid" it already can be seen.

If everything is working for you, I think this issue is ready for releasing it to main version (after adding translations for the new texts).

**Comment by arasaac-dga** [comment]
> I've just released to https://grid.asterics.eu/latest/ :
> 
> * don't play "speak label" if "play recorded audio" is existing on selecting an element
With "Speak custom text" is neccesary don't play too. 

> * added an info message if speak mode for collect element is "continuously" with direct possibility to change it: https://i.imgur.com/GKKte3m.png (don't know what the best description is here - do you have a better suggestion?)

The text is correct although is not on Crowdin to translate. The link to "Set action of global grid....." dont make anything. Perhaps must go to Edit Global grid?

> * For the default global grid, the text of the collect element is now spoken continuously -> I still have to change it for the default configurations, but for "start with empty config" or "reset global grid" it already can be seen.

OK

> If everything is working for you, I think this issue is ready for releasing it to main version (after adding translations for the new texts). 

Perfect.

**Comment by klues** [comment]
> With "Speak custom text" is neccesary don't play too.

OK, done.

> The text is correct although is not on Crowdin to translate. 

Now alll texts should be on crowdin, so please translate them.

> The link to "Set action of global grid....." dont make anything. Perhaps must go to Edit Global grid?

It's an action link, so clicking on it directly changes the speak action types of the current global grid. I've just added a confirm message and possibility to undo to make it clearer: https://i.imgur.com/IwIWum8.png

I've also updated the Catalan UTAC-CACE configurations and all default gridsets should now have "speak continuously" actions by default.

Everything is released to https://grid.asterics.eu/latest/ - so please test and give me your OK for releasing it to the main version.

**Comment by arasaac-dga** [comment]
Everything ok, tested and translated. Great work!!! Release it to the main version when you can.

**Comment by klues** [comment]
Published with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2022-11-22-15.05%2F%2B0100
