### ISSUE TITLE
Rename backups filename adding username (and date/hour) at download

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#224]
In order to make easier the backup's manage, it would be great if the username is added at the beginning of filename in order to better organize them when a professional manages several users. Consider adding the date and hour to the filename too.

**Comment by arasaac-dga** [comment]
Our proposal is add the username always at the beginning to order and group by user:

* for full backups: <username>_2023-01-16_15-58_asterics-grid-full-backup.grd
* for custom backups: <username>_2023-01-16_15-58_asterics-grid-custom-backup.grd
* for custom backups containing a single grid: <username>_2023-01-16_15-58_<gridname>.grd

**Comment by klues** [comment]
please test at https://grid.asterics.eu/latest/

**Comment by arasaac-dga** [comment]
Great. It's perfect!!

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-01-17-14.54%2F%2B0100
