### ISSUE TITLE
Zoom/Viewport issue on iOS / Android

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#231]
On iOS on Safari AsTeRICS Grid is cut at the bottom, because it's using `100vh` height of main element, which is the size of the viewport including the top address bar. It looks like this, at the bottom something is missing:
![grafik](https://user-images.githubusercontent.com/2537025/213706094-c96b2f77-7416-497b-aa53-1ccaf214e0f0.png)

On Android it's similar, something is missing, but then it becomes complete if the address bar hides after swiping up a little bit:
![grafik](https://user-images.githubusercontent.com/2537025/213706224-1b92887a-1e11-4af4-b342-fb26745878ce.png)

Ideally nothing should be cut at any time.
Also see this other issue, where this problem initially was reported: https://github.com/asterics/AsTeRICS-Grid/issues/219

**Comment by klues** [comment]
Please @rgabo74 and @arasaac-dga test at https://grid.asterics.eu/latest/ - it should be fixed now.

**Comment by arasaac-dga** [comment]
Yes. It is fixed. Great!!

**Comment by rgabo74** [comment]
Hi, I looks good to me. Thanks for the fix!
One suggestion to consider: I think it would be good to reset zoom too 100% when entering full screen mode. Even probably disable zooming by touchscreen.

Best regards,
Gábor
Sent from Yahoo Mail for iPhone


On Friday, January 20, 2023, 11:59 PM, arasaac-dga ***@***.***> wrote:




Yes. It is fixed. Great!!

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-02-10-12.55%2F%2B0100
@rgabo74 regarding your suggestion with resetting zoom, please open a new issue, if it's important.
