### ISSUE TITLE
Add Online Natural Language processing

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#242]
Beggining with Spanish, integrate in AG the Online Natural Language processing offered via ARASAAC API. 
Pending detail all the features, actions and options that it will neccesary to develop in AG to make work.

**Comment by klues** [comment]
@arasaac-dga with https://github.com/asterics/AsTeRICS-Grid/issues/182 we've again got the issue that speaking the same sentence multiple times in a row results in sending altered sentences to the API. It should now be fixed in "latest".

**Comment by klues** [comment]
released first version with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-05-31-13.40%2F%2B0200
