### ISSUE TITLE
iPad (5. Generation) > iPadOS 16.3.1 > Firefox 110.1 (28420) > full screen button has no effect

### ISSUE THREAD

**Issue by tectda17** [asterics/AsTeRICS-Grid#248]
Hi!

I love AsTeRICS Grid but unfortunately I can't let my 6 year old autistic son use it on my iPad because I can't make AsTeRICS Grid run in a **real** locked mode. What do I mean with "**real** locked mode"? I opened AsTeRICS Grid in the following browsers on my iPad:

1. Firefox 110.1 (28420)
2. Google Chrome 110.0.5481.114
3. Edge 110.0.1587.57
4. Safari (the one which is installed on my iPad with iPadOS 16.3.1).

Ad 1.) When using Firefox the full screen button has no effect.
Ad 2.) When using Chrome switching to full screen is possible to some degree - i.e. in "full screen mode" it's possible to close the AsTeRICS Grid tab, open new tabs, use the back, forward, refresh and some more buttons and the address bar.
Ad 3.) When using Edge switching to full screen is possible to some degree - i.e. in "full screen mode" it's possible to close the AsTeRICS Grid tab, open new tabs, use the login, back, forward, refresh and some more buttons and the address bar.
Ad 4.) When using Safari switching to full screen is possible - unfortunately Safari displays a visible button to turn off the full screen mode in the left upper corner (nearly exactly over the AsTeRICS Grid's home button) - when tapping on this button the back, forward, refresh and some more buttons and the address bar become visible.

Please see the attached PNGs.

It's absolutely necessary for me to make AsTeRICS Grid run in a real locked mode because my autistic son will tap on everything which is displayed on the screen and thus mess up all settings.

BR, David

![Firefox](https://user-images.githubusercontent.com/127306841/224046779-bb6877b1-10f3-4f54-971d-29608b0bb169.png)
![Chrome-Fullscreen](https://user-images.githubusercontent.com/127306841/224046850-1f592050-1b02-4f8d-a5db-91e8450453cf.png)
![Edge-Fullscreen](https://user-images.githubusercontent.com/127306841/224046880-2a196377-9179-41ca-937e-613847e19431.png)
![Safari-Fullscreen](https://user-images.githubusercontent.com/127306841/224046907-64978573-b2b7-452c-8362-3b63a4124e5d.png)

**Comment by klues** [comment]
Hello and thanks for contacting us!
It's strange that in Firefox also the menu isn't disappearing, which it definitely should. I'll have to take a look at it.
In general you'll have to "install" AsTeRICS Grid like an app, see [ARASAAC tutorial for installing on iOS](https://aulaabierta.arasaac.org/en/asterics-grid_ios_install). Afterwards you can use the OS specific functions for locking an app, for iOS this is called "guided access", see [ARASAAC tutorial for locking the app](https://aulaabierta.arasaac.org/en/asterics-grid-locking-application-on-android-ios) or the [Apple documentation for guided access](https://support.apple.com/en-us/HT202612)

**Comment by tectda17** [comment]
Hi!
THANKS for your fast reply.
With the information from [ARASAAC tutorial for installing on iOS](https://aulaabierta.arasaac.org/en/asterics-grid_ios_install) I could easily solve my issue. Thus, this was clearly a RTFM/RTBM/... issue - it's not enough to check out [Benutzerhandbuch (Englisch)](https://www.asterics.eu/manuals/asterics-grid/) - it's important to check out 
[ARASAAC Tutorial (Englisch)](https://aulaabierta.arasaac.org/en/asterics-grid_home) too.
By the way, on this page [AsTeRICS Grid – Installation as an app under Android](https://aulaabierta.arasaac.org/en/asterics-grid_android_install) one can find "Installat**t**ion with Google Chrome and Microsoft Edge" and "Installation in Opera web browser" but there is no description on how to install AsTeRICS Grid as an app under Android using **Firefox** (which pretty much works like the other web browsers).
At least I made a point with regards to the full screen button when using Firefox :-)
BR, David
