### ISSUE TITLE
Extend label translation feature to handle verb conjugation, verb tenses, irregular verbs, singular/plural nouns.

### ISSUE THREAD

**Issue by jamjolu** [asterics/AsTeRICS-Grid#252]
I propose allowing users to extend the translation feature (or something like it) to cover various word forms like verb conjugation, verb tenses, irregular verbs, singular/plural nouns, etc.
I can already do this by assigning a verb form like past tense to language I am unlikely to encounter. This is a hack that may have unwanted side effects, and likely results in the misuse of the "lang" tag.
Here is an example grid that uses my hack: https://drive.google.com/file/d/1SIagqH-UcPu3GlIDVsQ4qtVEhLF9r0ZC/view?usp=sharing

**Comment by klues** [comment]
Yes, we were already thinking of possibilities to support basic word inflections. Interesting that you've hacked the translation feature for it. It would also be possible to just clone grids and get the same effect by navigating. However I think there should be a native way. This is my current idea:

### New tab in edit modal
![grafik](https://user-images.githubusercontent.com/2537025/226847837-7f42c57d-4e7f-42f3-ab12-9b08c824da7f.png)

In this tab "Grammar" it would be possible to (optionally) define:
* type of word (verb, noun, adjective, ...)
* for verbs: conjugations (1st, 2nd, 3rd person, singular, plural, tenses) - the API from [verbix](https://verbix.com/) could help to insert all the conjugations automatically.
* for nouns: singular, plural, gender
* for adjectives: male / female form (for languages like spanish)

### Actions
There could be some automated actions like:
* selecting a noun automatically changes all verbs shown in the current grid to the correct conjugation
* the same for adjectives, the could also be adapted based on the currently selected noun

There could also be some actions to define manually (creating a separate element that performs it) like:
* changing the time of the last selected verb (or the verbs shown on the grids) to present, future or past
* changing the previously selected noun (or shown nouns in the grid) to singular / plural

@arasaac-dga, what do you think about it?

**Comment by jamjolu** [comment]
I have to think about this a bit. 
There are certainly constructs in English that could make automation based on a prior noun uncertain. For example:
In **times** like these, you need to be careful. (maybe tricky)
vs.
You should always be on **time**. (not so tricky)
This is just the 1st example that came to mind.
In any case, English has lots of complex rules that make natural language processing a huge project.

I like the Grammar tab idea in conjunction with an action, but maybe just a "Word Forms" tab. The action that would allow the user to toggle through a list of word forms. That would make the word form variations independent of grammar. An addition of a little visual prompt (like the little link box) such as a small + could inform the user that there are multiple forms available:
bike bikes 
easy easier easiest
run runs running ran

The verb "to go" needs 5 forms:
go goes going gone went

And the verb to be needs 8:
be am is are being been was were

In other languages that have more verb forms it could be tedious to toggle through the list.
In the case of verbs, an action associated with a navigation action from a noun or pronoun could stipulate which verb form to cue up. In English the verb with the most forms is "to be". But for most cases the infinitive form = 1st person present, 3rd person present, present participle (-ing endings), and past tense, would cover most cases in that order. Even this can result in complex situations:
I plan to go to the store.
I plan on going to the store
I go.
He goes.
I am going.
I am gone. 
The first 2 and the last 2 examples illustrate why cueing a verb form is not always simple to predict.

Another option would allow for a word form toggle button to be added to the Global grid that would modify the last entry in the collection element.

I am currently putting together a 5 X 4 grid set for English speakers that I hope will be expressive, flexible and efficient. It is the efficiency part that is most challenging, and verbs forms are most challenging. With the exception of the verb "to be", "to go" and "to do". I have to create 4 different grids for each set of 20 or so verbs I wish to include in my grid set. I have a special grid that covers some of the extra forms of the verbs "to be", "to go", and "to do" along with navigation buttons to the 4 basic different verb forms. This requires a lot of grid cloning and tedious label and sometimes navigation changes. The result often requires a lot of navigating on the part of the user to find the right verb. Many users will use the way a sentence sounds to ascertain its correctness. The ability to try various word forms without navigating may be helpful.

So far I have 108 elements in my grid set, and it is growing. And, I still haven't covered many nouns. My goal is to have something that will be mostly targeted to our students, but will have good support general English conversation. I will share my grid set when I feel it is complete enough for most users. It should serve as a good starting point for therapists familiar with "vocabularies" like "WordPower", or "Core First" found on dedicated speech devices.

My next grid set project will focus on the needs of early learners using a 4 selection or 8 selection gid set.

The addition of some method (even the simple toggle through various forms action) for accessing word form variations without creating an unnecessarily massive grid set would be most welcome.

Thank you for you consideration,
jl

**Comment by jamjolu** [comment]
I would also like to withdraw my prior suggestion about using the label translation action as a means to accommodate various word forms for two reasons:
1. Any grid edits that reorganize, add, modify  or delete buttons would require re-translating the entire grid to assure labels are correct between translations.
2. To make the translation less of a hack would require the addition of possibly dozens of additional language names, or the inclusion of additional identifiers for all the various tenses, conjugations, inflections, and other qualifiers (perhaps on another dropdown menu.) This seems unnecessarily complicated.
