### ISSUE TITLE
no speech output on RP4

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/AsTeRICS-Grid#26]
On an freshly installed RaspberryPi4 with Raspian OS (version 2019-09-26, based on Debian Buster), the Chromium browser does not produce audio (speech) output when items in the grid are selected. (Other sound output in the Chromium browser works).

**Comment by klues** [comment]
Maybe see: https://askubuntu.com/questions/761975/chromium-is-not-generating-voice
Try to install espeak or use Firefox.

**Comment by klues** [comment]
closed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2020-09-10-15.30%2F%2B0200
