### ISSUE TITLE
ResponsiveVoice API error (HTTP error code 502)

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#262]
Generally, when using responsivevoice it takes some time to get the speech output.
Unfortunately, it's also not deterministic if text-to-speech succeeds - sometimes yes, sometimes no.

In case of a failure the following error messages are shown at the developer tools console:

![signal-2023-04-24-135547_002](https://user-images.githubusercontent.com/4621810/233990452-a5a6c801-b82c-4c23-a97e-cafdb0a33e33.png)

The no ['Access-Control-Allow-Origin' error](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default) means that the server-side did not allow to use the resource, which actually does not make sense for an API.

Obviously this is a bug at responsivevoice. How to submit it?

**Comment by klues** [comment]
I've just investigated it and unfortunately I haven't found a good way to detect if TTS by responsivevoice has failed in the code. It's not allowed by their license to edit their javascript library and there is no built-in way: https://responsivevoice.org/api/
So the only possibility would be to write a wrapper for all console outputs and search for texts like `ResponsiveVoice audio could not be loaded`. Like this:

![image](https://user-images.githubusercontent.com/2537025/234019950-560c8d2e-9423-4feb-be88-76ed2983a6dc.png)

However a side effect of this is that I loose the possibility to track the origin (line of code) of all logs to console, which i don't want. So I think from our side this cannot really be optimized in terms of showing better error messages to the user.

Regarding contacting responsive voice: I've already did it via this link for two bugs: https://responsivevoice.freshdesk.com/support/tickets/new - however I did only receive a very general response not really addressing my reported bugs. So I think for users with a free license their will for support is limited.

**Comment by deinhofer** [comment]
What's strange is that I have the same CORS error when using opensymbols now:

![grafik](https://user-images.githubusercontent.com/4621810/234110926-71d539e5-e9a4-4a53-b425-03ef972b6cb2.png)

Did they all change their API? Or is it a browser problem?
