### ISSUE TITLE
Likely inconsistency between package.json and yarn.lock files

### ISSUE THREAD

**Issue by mjtc1985** [asterics/AsTeRICS-Grid#266]
Hello, 

I have a doubt related to the versions between package.json and yarn.lock files.

I tried to execute a a "yarn install --frozen-lockfile" command, but I got the following message:

error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.

Later, I executed a "yarn install" command, obtaining the following differences on my local files:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/25988639/235312045-75e5c97d-3f77-4231-b2f9-569592a8e76b.png">

I guess you are using yarn.lock file to generate a build for production environment, but package.json has other version for that libraries.

I´m not sure if the correct way is to update package.json or yarn.lock file, It depends on CI/CD process I think.

**Comment by klues** [comment]
Thanks for pointing that out!

I think it happened with [this commit](https://github.com/asterics/AsTeRICS-Grid/commit/5d45df20742b20f8b824ff4ac14722483493595a) where I've merged some things of https://github.com/asterics/AsTeRICS-Grid/pull/246

I think we should directly go to vue `2.7`, it shouldn't be a problem and then we can also remove `vue-template-compiler` according to this changelog: https://github.com/vuejs/vue/blob/main/CHANGELOG.md#vue-cli--webpack

**Comment by klues** [comment]
Today I've cleaned up and updated the dependencies with this commit: https://github.com/asterics/AsTeRICS-Grid/commit/bc18e25ea7f93e5a026722608320fe21624dd40c
I think this issue should be resolved now.

**Comment by mjtc1985** [comment]
Great!, thanks for the update.
