### ISSUE TITLE
problems with basque voice

### ISSUE THREAD

**Issue by Adipsiko** [asterics/AsTeRICS-Grid#269]
Hello, good afternoon.
I was trying to implement a communicator for a Basque-speaking child and I can't get the Basque voice to work. It does not appear as an option despite installing it. This happens only when doing it with windows.
if you could help me...
Many thanks for your work.
Thank you very much in advance.
Greetings

**Comment by klues** [comment]
As far as I see Windows 10 does not offer a offline TTS voice for Basque, see:
![image](https://user-images.githubusercontent.com/2537025/236193235-9e7a5e36-5583-4bb4-aab3-6ce3427bf96e.png)

Here an icon with a speech bubble is missing indicating that a voice is available.

Unfortunately I don't know if there are options for Basque voices, @arasaac-dga do you know?

**Comment by arasaac-dga** [comment]
We sorry but we have not experience managing TTS voices on Windows. On Android we know some basque voices to install but not on Windows.

**Comment by arasaac-dga** [comment]
We have made some tests (we have nor experience installing voices on Windows) installing AhoTTS Voices https://aholab.ehu.eus/aholab/ahosapi/ and only with Firefox we have seen in Asterics Grid Voices list Basque Voices from Aholab. In Chrome, Edge and Opera the Aholab installed voices are not listed. So, try with Firefox. Perhaps works.

**Comment by klues** [comment]
For me the hint from ARASAAC worked, I've installed AhoTTS (64bit), restarted the computer and now can use these voices in AsTeRICS Grid:
![grafik](https://user-images.githubusercontent.com/2537025/236230936-109b149e-1f4d-4c9d-852d-d9f15f50f7c4.png)

Maybe you have to restart your computer?

**Comment by arasaac-dga** [comment]
We have made several tests with Windows 10 and 11 and with all the web browsers installing 64bits AhoTTS voices. Our conclusions are:

* Windows 10: only see the voices listed on Firefox
* Windows 11: we don't see the voices on any web browser

What windows version and web browser do you use @klues? Do you see basque voices in all the web browsers? Anyway, we continue investigating it too....

**Comment by Adipsiko** [comment]
I keep testing.
In the configuration with Firefox, you can insert the voices in Basque, you can listen to the example sentence that comes by default, but when you try to use the communicator, with cells in Basque, I can hear when I press play when doing the sentence, but not every time I click on the cell. After a minute and I close the Firefox. This has happened to me on both computers.

**Comment by arasaac-dga** [comment]
> I have rebooted and tried on two different computers. They both have windows 10 and I can't get them to show up with chrome either. I have uninstalled and reinstalled the voice, and still not. On the other hand, with firefox, windows 10, yes, the voices appear but only for user offline.

No, "offline" is because the voice doesn't need internet to work but works with online and offline users. 

On the other hand, in our Firefox we listen without problem each cell when we press it and when you press play too. We are using the ARASAAC predefined communicator model in Basque to make the tests. Be sure that the cells have the the "Speak label" action added.

**Comment by Adipsiko** [comment]
yessss!! that was the mistake! There was no text in some of the cells.
Well solved then!
Thanks a lot!!!

**Comment by klues** [comment]
Great! 👍
