### ISSUE TITLE
Cell actions don't work

### ISSUE THREAD

**Issue by alexlucax** [asterics/AsTeRICS-Grid#273]
From a given moment the tables stopped performing the actions associated with the cells. I had to create a new account and import the tables. What is the possible cause of this problem?

**Comment by klues** [comment]
That's difficult to say. I would be great to have a screenshots or copy/pasted logs from the javascript console - you can open it with `Ctrl + Shift + I` or right click and `Inspect` anywhere on the page.

**Comment by klues** [comment]
Thanks, but unfortunately I can't see problems related to actions in these logs. Please open the logs again and then try to trigger the actions by clicking on the cells. I wonder if then there are any errors/logs in the console.

**Comment by klues** [comment]
I'm closing the issue because of too little information - please feel free to reopen or create a new issue, if the problem persists.
