### ISSUE TITLE
Touching tiles causing unwanted or ignored actions...

### ISSUE THREAD

**Issue by rgabo74** [asterics/AsTeRICS-Grid#276]
My kid is touching tiles longer than people would usually do. Because of this we are having the "directly selecting element on pressing mouse button" checkbox on, so the action is taken immediately.
Dependent on the duration of the touch there are unwanted behaviours happening when the tile have an action to switch to another grid.
 
Momentary touch: all good, switching to next grid normally
Bit longer touch (100-200ms): switching to next grid, but the tile on next page on the same position get activated
Even longer touch (longer than 200ms): switching to next page, no unwanted push of tile, but the next touch is ignored

This is happening on IOS, Safari browser

**Comment by rgabo74** [comment]
https://github.com/asterics/AsTeRICS-Grid/assets/11273702/abd3530b-fbc3-43a9-9a58-38a1b3aaf87a

**Comment by klues** [comment]
OK, I just tested on my Android device / Chrome where there aren't any additional actions on the second page as long as the finger wasn't lifted before (I think it should be like this). I don't have an iOS device at the moment, I think I'll be able to test on monday.

**Comment by klues** [comment]
Should be fixed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-06-02-11.40%2F%2B0200 - please test.
In order to keep speech output working, the first touch/selecting after opening the app may still be some kind of inconsistent. I needed to keep the `mousedown` event for the first time selecting something, because only with this event iOS allows speech output, the event `touchstart` isn't enough.

**Comment by rgabo74** [comment]
Yes, I confirm it is working as expected! Thanks a lot, Benjamin! Client is happy and approved the build! :)



Sent from Yahoo Mail for iPhone


On Friday, June 2, 2023, 11:48 AM, Benjamin Klaus ***@***.***> wrote:




Should be fixed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-06-02-11.40%2F%2B0200 - please test.
In order to keep speech output working, the first touch/selecting after opening the app may still be some kind of inconsistent. I needed to keep the mousedown event for the first time selecting something, because only with this event iOS allows speech output, the event touchstart isn't enough.

**Comment by klues** [comment]
Great, I'm happy to hear that! 🥳
