### ISSUE TITLE
Disable pop-up messages in full screen mode

### ISSUE THREAD

**Issue by rgabo74** [asterics/AsTeRICS-Grid#282]
My kid is using the grid in full screen mode. Pop-up messages for backup reminder or new version are coming up and covering half of the screen on the small phone screen what he is using. He can't close it, so it is blocking him to use until we recognise the situation can close the message. 

A suggestion for resolution would be to disable pop-ups when the grid is in full screen mode.

**Comment by klues** [comment]
I've implemented this:
* no popups are shown in locked mode anymore. Fullscreen has no effect on popup visibility, but locked state has.
* the last popup is stored and shown at leaving the locked state.

Please test at https://grid.asterics.eu/latest/
You could test with playing a webradio in locked mode (shows popup of currently running radio) or setting backup interval reminder to 1 day in the settings (and change something in the grids to be reminded).
