### ISSUE TITLE
Ensure that "Restore Backup from file" or "Restore Default Communicator" option really delete all the actual boards and clean the account

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#291]
Ensure that when using the "Restore Backup from file" or "Restore Default Communicator" option, all boards are deleted. We have found some users in which there are like layers with different backups superposed. We explain it. It seems that in some cases (perhaps when there is not good conexion) when a user restores a backup the actual one is not deleted completely and the new backup is superposed over the original (but you don't see the original). So, in some cases when we have used the option "Restore Default Communicator" we have seen the backup under the actual one (an old one). In one case we have to press three times ""Restore Default Communicator" until we reach a clean communicator. So, in some way, in some cases a backup is superposed above another not completely cleaned. So, it could be interesting to set additional control to assure that the communicator is really restored to default in all situations.

**Comment by arasaac-dga** [comment]
Ok, thanks for the information. We hadn't see the issue solved about this on https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-05-26-10.14%2F%2B0200 So, the best it's yo keep watching and see if this fix don't generate more problems after 2023-05-26 or if there is someone the problem is due to restoring a backup before this date. Thanks

**Comment by klues** [comment]
I'll close this issue, feel free to reopen if the problem occurs again.
