### ISSUE TITLE
Option to see whole text in the accumulated phrase (without cut off)

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#300]
Add an option in the settings page to enable the possibility to see the whole text in the accumulated phrase without cut off as it is now (centring the picto in the middle of the text).

**Comment by arasaac-dga** [comment]
Yes. Works great!! Perhaps the option is something hidden for users now (although is its place) but we consider, when it's possible, that configuration page must be "redesigned/reconfigured" to include all configuration options of the communicator (although with a logic and usable organization). So, for us, leave it as it is now.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-10-10-09.52%2F%2B0200
