### ISSUE TITLE
Force to upper/lower case in settings page is not apply when generating a PDF.  

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#303]
Force to upper/lower case in settings page is not apply when generating a PDF.

**Comment by klues** [comment]
Fixed and released to "latest", please test.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-10-10-09.52%2F%2B0200
