### ISSUE TITLE
Export to PDF whole grid although there are empty rows

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#304]
When generating PDF if the grid has, for example, 5 rows and you have only created cells for the first two rows, when exporting to PDF it only shows the two rows created, so the cells are deformed. The PDF has to respect the number of rows and columns of the board although the cells are empty (not created).

**Comment by klues** [comment]
released to "latest", please test.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-10-10-09.52%2F%2B0200
