### ISSUE TITLE
Block back and forward navigation gestures on iOS Safari when Asterics Grid is in locked mode

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#309]
Prevent (block) that user can use back and forward navigation gestures on iOS Safari when the communicator is locked. It's neccesary to block these gestures in order the Asterics Grid's user only use the predefined methods to navigate between grids (linked cells or home button). See video attached https://app.box.com/s/q28g7ahqskk3sd6ihzxn9fbkhg5urcua to see the problem.  Documentation about how block this gestures https://pqina.nl/blog/blocking-navigation-gestures-on-ios-13-4/

**Comment by klues** [comment]
Yesterday I've briefly looked at this issue and found out that the workaround in the link doesn't work anymore. The only possibility seems to be to completely "disable" the browser navigation history, which results in:
* if used as "installed app": no navigation within the app using the gestures in iOS
* if AsTeRICS Grid is used in the browser: no navigation within the app using iOS gestures, but also no navigation using the browser's "back" button in all browsers. However the back gesture or back button still navigates to the page that was opened before AsTeRICS Grid within the browser.

@arasaac-dga: do you think we should change it like this? It would solve the issue, but also disables browser navigation within the app for everyone.

**Comment by arasaac-dga** [comment]
We think that disabling all the gestures in all the navigators it's not a bad policy because users don't need them using AG and avoid future problems (like the zoom in the past). Users have defined the navigation actions inside the communicator that allow them to move between all the grids and features, so they don't need additional gestures. Is it possible to disable gestures only when the communicator is blocked (as you made for zoom gesture/feature)?. Disable only in blocked mode allows administrators to use them. Anyway, administrators don't think that gestures help them to manage AG and usually use it in PCs where gestures are not used. They have the left menu that allows them to manage all the communicators and navigate to all sections. Finally, we use to recommend to install as APP. So, we understand by your comments that in this case it would be less problematic due that there is no back button in navigator. 

Do you agree @klues? What do you think? We do not have a defined opinion about what is the best, although if it's possible to only disable in locked mode sure will do it.

**Comment by arasaac-dga** [comment]
Yes, ok. We also think that not many professionals use gestures to navigate through history. So, for us, ok disable it. Thanks

**Comment by klues** [comment]
Released to https://grid.asterics.eu/latest/
Please test on different devices, if navigation (in menu and grids) is still working as expected everywhere.

**Comment by klues** [comment]
I've just had an idea of a better, cleaner and more maintainable solution. So maybe please still wait before doing extensive testing.

**Comment by arasaac-dga** [comment]
Ok, great. We have tested this iniciatial fix in our iPad and works but, of course, if you find cleaner and more maintainable solution much better ;-) So we wait!!!

**Comment by klues** [comment]
I've now implemented the "cleaner" solution, however it's still hacky in some way 🙈 
See https://grid.asterics.eu/latest/

Differences to previous solution:
* better: navigation using gestures and back/forward buttons is still possible, if not locked
* better: links in the menu are actual links referring to a hash like `#settings` instead of `javascript:void(0)`
* worse: on iOS swipe back is still doing something in locked mode, it shows the previous page shortly and then comes back to the current one

For me I like this solution a little bit better,  but I'm still not super happy because of the third point. Tell me what you think. @Apple: why do you have to do everything differently?! It's like the new Internet Explorer.

**Comment by arasaac-dga** [comment]
We have tested and this solution has another bad consequence on iOS. After you have locked a communicator, when you unlock it, if you go to the settings page, for example, the scroll doesn't work. You have to close the APP and open it again. So, we don't think this is a good solution at the moment because we have confirmed the other bad consequence that you have commented and don't like the effect. So, perhaps, is better the other one as a temporal solution or give more time to find an effective solution on all operating systems.

**Comment by klues** [comment]
Thanks for finding this bug! It's not related to the navigation itself, but to the preventing of the zoom in locked mode in combination with the back navigation. But I've fixed it now, so please test again.

**Comment by arasaac-dga** [comment]
Yes, now works. Great!!!

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-06-28-10.11%2F%2B0200
