### ISSUE TITLE
Falla en la reproducción de la frase

### ISSUE THREAD

**Issue by gaalmg** [asterics/AsTeRICS-Grid#321]
Hola! Esta última semana que he estado usando la aplicación al darle el botón play tarda mucho en reproducir la frase, así como en corregirla, ya lo he probado en diferentes dispositivos y en todos funciona igual, me parece que fue con la ultima actualización

**Comment by arasaac-dga** [comment]
Ahora ya funciona. La causa de los problemas que comenta han sido labores de mantenimiento en el servidor de ARASAAC que ofrece el servicio y que, por tanto, no devolvía las frases corregidas adecuadamente. Ya está funcionando de nuevo.

**Comment by klues** [comment]
OK, thanks ARASAAC for responding. I'll close the issue. @gaalmg: if you're still experiencing problems, please comment again or open a new issue.
