### ISSUE TITLE
Basque voice synthesizer

### ISSUE THREAD

**Issue by jlaquidi** [asterics/AsTeRICS-Grid#324]
Greetings.
First of all I want to thank you for the extraordinary contribution that this communicator represents.
Its features are impressive, but the Basque voice synthesizer is missing, it is not present among the numerous options.
Both the application language and the cell content can be configured in this language, but speech synthesis is not available. There are voice synthesizers that can be used for free and if they were added to the configuration options it would be of great help to us.
Thank you very much in advance for your attention.
All the best

**Comment by klues** [comment]
Glad that AsTeRICS Grid is useful for you! 🎉 

The voices of AsTeRICS Grid are dependent on the voices that are installed on the operating system where AsTeRICS Grid runs on. For further understanding you can read this: https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/10_faq.md#issues-with-online-text-to-speech-voices-lags-not-working

There are possibilities to install additional voices on the operating systems, see https://github.com/asterics/AsTeRICS-Grid/edit/master/docs/documentation_user/10_faq.md#installing-additional-voices

For Windows and iOS I didn't find a solution to install a Basque voice, but maybe for Android there is. In the [tutorial from ARASAAC](https://aulaabierta.arasaac.org/en/dynamic-communicator-asterics-grid-installation-of-speech-synthesis-tts-android) they're writing about "AhoTTS" for Android where it seems they have a Basque voice.

As an alternative you can select "Show all voices" in the settings:
![image](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/d9282c59-389b-4315-9f2c-9e12dab85520)
and then select a voice in a different language that is similar to Basque (e.g. Spanish), if this makes any sense and the pronunciation of the languages is similar enough.

**Comment by jlaquidi** [comment]
Hi Benjamin,

I'll try.
Thanks for your quick response.

Greetings

**Comment by klues** [comment]
OK, I'll close this issue - if you have more questions, maybe it's best to directly contact ARASAAC on Instagram, Facebook or via mail, because they for sure have more experience regarding this question.
