### ISSUE TITLE
Play recorded audio isn't working after the latest version

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#326]
Moved this issue from the Asterics project as it was in the wrong repository: https://github.com/asterics/AsTeRICS/issues/361

## Original post

Please, after the last update version, all the cells that contains play recorded audio doesn't working.
Sorry, my video is it in portuguese language.
I'm from Brazil.
See when put the button "test" the audio doesn't working, but when put the button "play" the audio is OK.

**Comment by klues** [comment]
released to grid.asterics.eu/latest/ - please test.

**Comment by deinhofer** [comment]
Just tested it on Linux and Windows. Problem fixed, so please release.

**Comment by klues** [comment]
released to main version with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-10-12-15.47%2F%2B0200
