### ISSUE TITLE
Natural/alphabetical/international sort in dropdown menu

### ISSUE THREAD

**Issue by mtrakal** [asterics/AsTeRICS-Grid#333]
We have drop down menu with country / language selection on many places (I think, that it sould be used on all lists, not just countries, because every list can contain localized non-ascii strings).

But list is not properly sorted for non-ascii non-us characters. Like in Czech we have non-standard ěščřžýáíéó.
But expected sort/order is not on end of list, but for example: `C D E É Ě F G H I Í J K L` ... not `C D E F G H I J K L ... É Ě Í`

More info about International sorting for example here: https://medium.com/quick-code/how-to-sort-an-array-of-strings-with-non-latin-letters-7414328c0205

![image](https://github.com/asterics/AsTeRICS-Grid/assets/1458891/7107ae70-60af-40ed-a0cc-eb09fbeedb01)

**Comment by klues** [comment]
congrats to issue #333 😄 

Thanks for the hint, this was an easy one, see https://github.com/asterics/AsTeRICS-Grid/commit/e4cb13946ed1ee8b2e90073bdcb6c972e6946e7e
Please test at https://grid.asterics.eu/latest/ where now also the Czech app language can be tested.

**Comment by mtrakal** [comment]
@klues thank for fix on latest version works fine :) 👍

**Comment by klues** [comment]
Now released to main version, see https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-10-27-14.58%2F%2B0200
