### ISSUE TITLE
Automatic Return to Home Page

### ISSUE THREAD

**Issue by msantos-87** [asterics/AsTeRICS-Grid#345]
Option (switch on/off in the settings) that after pressing a button in a subpage, the board automatically returns to the home page of the board, hence eliminating the extra click to 'home'.

**Comment by msantos-87** [comment]
Working perfectly in Macbook Safari, Chrome and Firefox and in iPad Safari. (Also iPad Firefox but I can't set the Grid to fullscreen on there. It might work once I do all updates, though, it's an old iPad ;) ) And in Android mobile. Thank you! =)

**Comment by klues** [comment]
Great, thanks for testing! I'll keep the issue open until I've released it to the main version (not "latest").

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-01-03-12.25%2F%2B0100
