### ISSUE TITLE
keep the chronology also when the home grid is selected 

### ISSUE THREAD

**Issue by gianlutra** [asterics/AsTeRICS-Grid#356]
During the navigation between the grids it is always possible to return to the previous ones unless you open the home grid: in that case the chronology is reset. It would be convenient to keep the history even when the home network is selected.
Thanks

**Comment by klues** [comment]
Thanks for your issue / comment.

Currently it's implemented like this: the history of navigation is reset, if you come to a grid which is already in the history.
So if the history is `Grid 1` -> `Grid 2` -> `Grid 3` and then there is a navigation to  `Grid 1` again, the history is reset. For most cases the navigation starts at the home grid, so when coming back to the home grid, the history is reset.

Of course it could be changed. I could store the whole history and maybe only discard the oldest one, when it's longer than e.g. 100 elements.
@arasaac-dga what do you think?

**Comment by arasaac-dga** [comment]
In our opinion, it's ok as is now. We consider that is the most logic to reset the history navigation when you arrive to home grid. Anyway, is our opinion.

**Comment by klues** [comment]
OK, then I'll close the issue. @gianlutra if you really need it, please comment again explaining why it's important and re-open the issue.
