### ISSUE TITLE
Language dropdown

### ISSUE THREAD

**Issue by msantos-87** [asterics/AsTeRICS-Grid#364]
When selecting a language for the word forms (#254) it just shows the two-letters code and not in alphabetical order which makes it harder to find the desired language. It would be good to have it the same as the dropdown version when you translate the grid where it names the language as well as the code so it's not necessary to know the codes by heart e.g. "German (de)".

Respectively, as discussed by email, I'd anyway need more nuanced language options, like this https://www.localeplanet.com/icu/index.html.

**Comment by klues** [comment]
Language dropdown is fixed at "latest". For additional languages please open a new issue describing what you would need exactly (only some new language codes or the possibility to freely define new languages).

**Comment by msantos-87** [comment]
Thank you!

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-03-20-08.17%2F%2B0100
