### ISSUE TITLE
Implement import/export from OBF (Open Board Format)

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#37]
@willwade suggested to implement import/export of OBF, see https://www.openboardformat.org

**Comment by willwade** [comment]
This may be of use: https://github.com/hosseinamin/pasco/commit/651d4382b49cc46178545a0398a37b753a9f0d76

**Comment by sabicalija** [comment]
Is this a proposed format or already an "official" specification?

**Comment by willwade** [comment]
Its as "official" as you can get. See current users of the format: https://www.openboardformat.org/partners

@whitmer is the author of this - but always open to improvements

**Comment by klues** [comment]
OBF import is implemented in the [current release](https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2020-04-24-13.10%2F%2B0200), also see [documentation](https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/02_navigation.md#additional-options).

I've opened a follow-up issue #47. If you would benefit from OBF export, please comment there.
