### ISSUE TITLE
Asterics grid just keeps loading, I can enter editing mode

### ISSUE THREAD

**Issue by MiraMiraS** [asterics/AsTeRICS-Grid#378]
Since of yesterday, I have trouble using AstericsGrid. I can access editing mode and see all the grids, but in view mode it just keeps loading, but nothing happens. There was a update, so I think it might be a bug.
 I tested it on a 2 different computers ( win 11, Linux mint), and on on tablets ( Samsung, android 13 and 14 and Lenovo, android 10) and my phone.  Then I used different browsers ( Chrome, Edge, Firefox), and it was the same.  I don't have offline users, so I couldn't test that.
Two weeks ago the same happened on a 2 old tablets, but I was sure that was just that they were too old for app to support it.
Please help, because I have a lot of nonverbal students who are using Asterics Grid on a daily basis. Thank you 
![Screenshot_20240406_072808_com android chrome](https://github.com/asterics/AsTeRICS-Grid/assets/166199732/7e1d3243-d2ee-4b79-b7b1-57dd9bbeae4c)

**Comment by MiraMiraS** [comment]
Update: It works when global table is activated, otherwise it keeps loading...

**Comment by klues** [comment]
Thanks for reporting the bug! I'm sorry, it was a bug I've introduced while fixing another bug 🤦‍♂️ 
It should be fixed now: https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-04-08-08.28%2F%2B0200

**Comment by MiraMiraS** [comment]
Thank you so much for your help. Have a great day.
