### ISSUE TITLE
No se oye la frase 

### ISSUE THREAD

**Issue by Logo2ca** [asterics/AsTeRICS-Grid#382]
Hola, 
Hemos implementado el comunicador a un alumno y no se oye la frase al pulsar la celda correspondiente. 
Ocurre también que se escucha con demora de 5 minutos.
Gracias

**Comment by klues** [comment]
Hello,
I'm quite sure that the reason are the online voices by Responsive Voice, which unfortunately aren't very reliable. See https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/10_faq.md#issues-with-online-text-to-speech-voices-lags-not-working for more details. This document also describes how it's possible to install offline voices on different devices.
If there are more questions, just ask, but for now I'll close the issue.
