### ISSUE TITLE
Possibility to swap text and picture for one cell

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/AsTeRICS-Grid#390]
If covering the label with your finger it would be very nice to swap the position of text & pictogram.

**Comment by klues** [comment]
I don't fully understand. So not an general option to show labels above the pictorgrams, but only for one single cell? When should the swap happen?!

**Comment by klues** [comment]
OK, this is already included in https://github.com/asterics/AsTeRICS-Grid/issues/168, so I'll close this.

**Comment by klues** [comment]
now ready to use in main version with release https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2025-01-27-08.34%2F%2B0100
