### ISSUE TITLE
YouTube Action "Volume Up" increases volume by at least 50% regardless of increment setting

### ISSUE THREAD

**Issue by jamjolu** [asterics/AsTeRICS-Grid#405]
As stated in the title, the YouTube Volume Up action increases the volume by 50% + the incremental setting (like 5%) defined in the action if the current volume is set at 0%. If the volume is a little above 0%, like 10%, a single Volume Up action causes the volume to jump to 100% even if the volume increment is set to 0%.

The YouTube Volume down action works fine.
jl

**Comment by klues** [comment]
Thanks for reporting, I've fixed it in https://grid.asterics.eu/latest/ - please test.

**Comment by jamjolu** [comment]
It works fine,
Thanks,
Jim Luther

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-06-19-12.08%2F%2B0200
