### ISSUE TITLE
Updating grid.asterics.eu/latest/ fails

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#42]
Just (March, 25th, 2020) tried to open the latest version of the grid, but it fails, see screenshot:

![image](https://user-images.githubusercontent.com/4621810/77527173-f9485c80-6e8b-11ea-8edb-d033d94f1a1a.png)

Both for Firefox and Chrome

**Comment by klues** [comment]
should be fixed now, see https://grid.asterics.eu/latest/#main
