### ISSUE TITLE
Action to change volume of speech synthesis voice

### ISSUE THREAD

**Issue by ms-mialingvo** [asterics/AsTeRICS-Grid#420]
The in-built buttons to increase and decrease the voice volume on a device are only accessible to some AAC users, due to motor issues etc. So my request would be to have an action in Asterics to increase/decrease the volume of the voice, so it's as easily accessible as e.g. volume of youtube currently.

**Comment by klues** [comment]
Added a new action `System action`, where it's possible to change the system volume:
* text-to-speech is played with system volume
* webradio and youtube volume is played with [radio/yt volume] x [system volume]

I've released it to latest, you can test it with the backup in the attachment, where I've added system volume elements to the global grid.
[test2_2024-09-19_12-36_asterics-grid-full-backup.zip](https://github.com/user-attachments/files/17057698/test2_2024-09-19_12-36_asterics-grid-full-backup.zip)

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-10-10-09.52%2F%2B0200
