### ISSUE TITLE
Scanning select key: When recording key hold duration is set by default

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#43]
By the default, the scanning input method has the ```space``` key with hold duration configured for element selection. If you record a new key, e.g. ```CtrlRight``` the selection should be done without hold duration. As the duration value is hidden within the folded tab ```more```, it took me a long time to understand that I had to press the button for the period of ```hold duration```.

![Screenshot from 2020-03-25 12-13-56](https://user-images.githubusercontent.com/4621810/77535721-631c3280-6e9b-11ea-84ba-de54c523feef.png)

## Solution

a. Clear hold duration when recording a new key
b. use two different keys without hold duration by default (should be more obvious for the first try)

**Comment by klues** [comment]
yeah, you are correct, this is confusing if you don't know about it.
I've implemented solution (a), see https://grid.asterics.eu/latest/#main

**Comment by deinhofer** [comment]
Thanks for the fast fix!! Looks good to me :-)
