### ISSUE TITLE
Import obf/obz

### ISSUE THREAD

**Issue by ms-mialingvo** [asterics/AsTeRICS-Grid#432]
Import works fine on Macbook (and I assume Windows computer). It doesn't work on the iPad and iPhone (ios 17.7), the file is greyed out and it's not possible to select it.
Obf is working on Windows and Samsung tablet, my internet connection is too slow to test if obz also works but I assume it does then so it seems it's only Apple where it's an issue. Edit: Yes, obz works.

**Comment by klues** [comment]
Probably fixed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-11-06-11.43%2F%2B0100

**Comment by ms-mialingvo** [comment]
It's still not working, not sure if you understood the issue correctly. I can't open/import .obf and .obz files in the iPad, be it through 'restore backup from file' nor through 'import custom data from file'. I can't select these files.

**Comment by klues** [comment]
Ok, I think I've fixed it now. Please test at latest, should be there in about 10 Minutes.

**Comment by ms-mialingvo** [comment]
Yes, it works in the latest version! :) You can release it.

**Comment by ms-mialingvo** [comment]
(Just fyi, nothing is greyed out anymore, even files that are not possible / make no sense to import. I don't know if that's on purpose. It doesn't bother me.)

**Comment by klues** [comment]
Great! Theoretically not all files should be selectable, only files that are somehow a zip archive or in json format. Unfortunately iOS doesn't supports filters by file extension like `.obz`, but only by mime type, which is more generic. I'll test what happens if I select any other zip file before releasing, it should just import nothing.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-11-15-11.54%2F%2B0100
