### ISSUE TITLE
Toggle between languages

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#435]
Feedback from hospital: it would be good to have the possibility to toggle content languages with a single element.

**Comment by klues** [comment]
@arasaac-dga @ms-mialingvo if you want, you can also test this at "latest".
There is now a new possibility to change to the last used language and therefore creating a button for toggling the language:
![grafik](https://github.com/user-attachments/assets/9a727453-993a-4a39-b576-38dedd4fc396)

**Comment by ms-mialingvo** [comment]
Oh, this is cool!

**Comment by arasaac-dga** [comment]
Great!!! We like it.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-11-06-11.43%2F%2B0100
