### ISSUE TITLE
Active input options not obivous

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#44]
If you open a grid, it's not clear which **input options** are active. This can be confusing if default **scanning** and default **direction input*** was activated by a previous configuration.

 Pressing <kbd>space</kbd> leads to 

* select next scanning group
* speak out first element of grid every time

![image](https://user-images.githubusercontent.com/4621810/77537514-85fc1600-6e9e-11ea-94ee-1bc154f7f397.png)

## Solution

Visualize 
* active input options in the popup-menu and
* visualize a navigation info above the grid, e.g.:
  * Scanning: Next: <kbd>space</kbd> Select: <kbd>ctrl-right</kbd>, Direction input: Select: <kbd>space</kbd>

**Comment by klues** [comment]
Thanks for the suggestion, visualization of active input options is now implemented.
see http://prntscr.com/rmkdmm or https://grid.asterics.eu/latest/#main

Regarding visualization of information for navigation above the grid: it would be somehow nice, but on the other hand - who really needs it? the normal user should know about his input options and for the configuring user the visualization within the contextmenu should be sufficient.

**Comment by deinhofer** [comment]
much better, thanks!!

The visualization would nevertheless improve the usability, I think.
At least with Asterics models I think it's hard for somebody opening a new model to find out how to operate it.

**Comment by klues** [comment]
Thanks for suggesting ;)

You mean if input options with an AsTeRICS model in the background are used within AsTeRICS Grid? Oder AsTeRICS models in general?

**Comment by deinhofer** [comment]
> Thanks for suggesting ;)
> 
> You mean if input options with an AsTeRICS model in the background are used within AsTeRICS Grid? Oder AsTeRICS models in general?

No, also without the Asterics Grid.
e.g. imagine you are a therapist and manage several grids for your clients. Then it should be easy to get the operation mode not having to check some hidden configuration dialogues first.
But for sure it's nothing with high priority. Maybe let's wait if similar feedback arises from somebody else.

**Comment by klues** [comment]
Yeah, in some cases it surely would be a benefit. But I think I would not display the information by default (unnecessary for normal users), but only show it on a specific keyboard combination like e.g. `Ctrl + I` for "input options". I think this feature is only needed by "power users" which can also remember keyboard shortcuts.

**Comment by klues** [comment]
I'll close this issue since the highlight of active Input options is already implemented. If the need of more information about input methods emerges again in the future, let's open a new issue.
