### ISSUE TITLE
Traspasar tableros

### ISSUE THREAD

**Issue by Celesteroma** [asterics/AsTeRICS-Grid#443]
Hola,
Me pongo en contacto con ustedes para proponer una sugerencia. Sería muy útil poder traspasar tableros de un usuario a otro, al igual que se puede clonar un tablero poder hacer lo mismo, pero clonarlo para otro usuario. Ahorraría tiempo, el que se pierde creando tableros idénticos para usuarios diferentes. 
Gracias.
Atentamente,
Celeste Rodríguez Martín

**Comment by fevisera** [comment]
Hola @Celesteroma,

No soy experto en la aplicación ya que llevo poco tiempo usándola, pero he notado que existe una opción para exportar e importar tableros. Aunque no es exactamente la funcionalidad que mencionas, podría facilitar el proceso de compartir tableros entre diferentes usuarios. Ya nos dices si te resulta útil.

**Comment by ms-mialingvo** [comment]
Hola @Celesteroma . Como explicó Fevisera, puedes exportar un tablero e importarlo para otro usuario. Además, El programador está trabajando en una opción para publicar y compartir tableros de forma pública. (#29) Pero sí los tableros que quieres compartir obtienen informaciones y datos personales (por ejemplo fotos de personas) es mejor utilizar la option exportar/importar.

@klues This can be closed as it's already covered in 29 respectively in the existing options.

**Comment by Celesteroma** [comment]
Ya lo he averiguado! Disculpad las molestias, gracias!
