### ISSUE TITLE
Register button stays greyed out

### ISSUE THREAD

**Issue by roopeux** [asterics/AsTeRICS-Grid#454]
After filling in required information on https://grid.asterics.eu/#register, the register button does not react to click.

<img width="1233" alt="image" src="https://github.com/user-attachments/assets/e684fee7-4dbf-4cdc-9b84-a11a910d36fd">

Mac M1 with Chrome Version 129.0.6668.101 (Official Build) (arm64)

**Comment by ms-mialingvo** [comment]
Is it possible that the username isn't valid? I see something "characters" in the screenshot, it should state "valid username".

**Comment by roopeux** [comment]
That was it.  A UX idea might be to allow caps in the UI but lower-case them in the code.
