### ISSUE TITLE
Error ususario davidducuara

### ISSUE THREAD

**Issue by davidducuara1** [asterics/AsTeRICS-Grid#456]
Buenos días,

Hoy no se conecta el usuario "davidducuara" en su tablet. He probado en distintos dispositivos y con distintas redes y salta siempre el mismo error. El error dice "Error al iniciar sesión (error de red), por favor inténtalo de nuevo más tarde". 

Sin embargo, en mi ordenador, que ya está logueado, puedo utilizarlo sin problema (conjuga verbos, así que sí que se conecta a la red), pero si intento loguear al usuario en ese mismo ordenador, en un navegador diferente, aparece también este error.

No sé si está caído vuestro servidor o es un error que ha dado al haber ampliado bastante el panel en el día de ayer...

Gracias por vuestra labor. Un abrazo. Miriam.

**Comment by ms-mialingvo** [comment]
The boards aren't currently synchronising on the cloud. So I think there is an issue with the AsTeRICS server right now.

**Comment by deinhofer** [comment]
Unfortunately the authentication server is down at the moment. We are working on it.
Please be patient.

**Comment by klues** [comment]
works again, thanks @deinhofer for investigating! 👍

**Comment by ms-mialingvo** [comment]
@deinhofer The syncing is not working again.

**Comment by klues** [comment]
Sorry, we had multiple server issues on the weekend, probably mostly related to problems at our hosting provider. It should work again and we hope it will last longer now ;)
