### ISSUE TITLE
Use locale specific link for help

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#46]
As the help for Asterics Grid currently is only in English and it's not clear when the asterics webpage would get support for several languages, I would suggest to link to the respective locale-specific page using google-translate.

## Example

If the configured locale in the Asterics Grid is **de**, the **Help**-link (also when pressing <kbd>F1</kbd>) should open the [german help of Asterics Grid](https://translate.google.com/translate?sl=en&tl=de&u=https%3A%2F%2Fwww.asterics.eu%2Fmanuals%2Fasterics-grid%2F).

The translation is already rather good and if not it's easily possible to check the original wording in English.

**Comment by sabicalija** [comment]
We could generate those links automatically.

**Comment by deinhofer** [comment]
> We could generate those links automatically.

Do you mean providing a menu on www.asterics.eu with locale-specific links?

**Comment by sabicalija** [comment]
It could be a dropdown menu in the navbar for some languages. The links for the dropdown could be automatically generated.

![image](https://user-images.githubusercontent.com/13609768/79559732-9327b180-80a6-11ea-8c9f-09964880041f.png)

**Comment by deinhofer** [comment]
> It could be a dropdown menu in the navbar for some languages. The links for the dropdown could be automatically generated.
> 
> ![image](https://user-images.githubusercontent.com/13609768/79559732-9327b180-80a6-11ea-8c9f-09964880041f.png)
> 
> The link could open in the current or a new tab.

good idea!!
Maybe do both?

**Comment by sabicalija** [comment]
> good idea!!
> Maybe do both?

Sure.

> ## Example
> If the configured locale in the Asterics Grid is **de**, the **Help**-link (also when pressing F1) should open the [german help of Asterics Grid](https://translate.google.com/translate?sl=en&tl=de&u=https%3A%2F%2Fwww.asterics.eu%2Fmanuals%2Fasterics-grid%2F).

But where is the locale stored/configured in Asterics Grid? How about other repositories?

**Comment by klues** [comment]
What do you mean by "do both"?! Open the link in the current and in a new tab?! 😄 

I could can change the links within AsTeRICS Grid according to the currently used locale. However in the case that the user uses the german version of AsTeRICS Grid, but is also able to read in english (which will be the case quite often) it would be better to show the english version of the help. So I'm not 100% sure which is better: automatic translate with possibility to switch back oder automatic original with the possibility to translate manually?!

**Comment by sabicalija** [comment]
> What do you mean by "do both"?! Open the link in the current and in a new tab?! 

No, but we could "open the help with F1" (1) and "provide links in the navbar" (2). ;-)

**Comment by deinhofer** [comment]
> What do you mean by "do both"?! Open the link in the current and in a new tab?! smile
> 
> I could can change the links within AsTeRICS Grid according to the currently used locale. However in the case that the user uses the german version of AsTeRICS Grid, but is also able to read in english (which will be the case quite often) it would be better to show the english version of the help. So I'm not 100% sure which is better: automatic translate with possibility to switch back oder automatic original with the possibility to translate manually?!

I think it's good to directly link to the translated page as it's easily possible to switch back to English or see the original wording when hovering over a certain location, see screenshot:

![image](https://user-images.githubusercontent.com/4621810/79744438-9caf5480-8306-11ea-8ab5-4f425d7b77e4.png)

**Comment by deinhofer** [comment]
> > What do you mean by "do both"?! Open the link in the current and in a new tab?!
> 
> No, but we could "open the help with F1" (1) and "provide links in the navbar" (2). ;-)

exactly!! ;-)

**Comment by sabicalija** [comment]
Hi,

hab jetzt den Build hochgeladen (https://www.asterics.eu/next/).

Bin auch schon auf ein Problem gestoßen. CSS passt nicht ganz.

![image](https://user-images.githubusercontent.com/13609768/79803742-dc0b8e80-8362-11ea-85bb-2cf6ca3dcf24.png)

Das liegt daran, dass die Klasse "theme-default-content" nicht gesetzt ist. Sobald man diese über die DevTools einträgt, schaut's auch wieder richtig aus.

![image](https://user-images.githubusercontent.com/13609768/79803781-f3e31280-8362-11ea-9500-8ceb897f205e.png)

Wenn man genau schaut, dann siehst man auch dass der Settings-Button (Bild 1 - 1) und das Dropdown-Menü für die Sprachen (Bild 1 - 2) fehlen. Vuepress baut ja beim Build zwei Versionen. Google Translate bekommt die Server Variante. Daher sieht die auch etwas anders aus. Die Settings machten nicht viel Sinn für den Server, deshalb hab ich Ihn auch deaktiviert. Außerdem könnte man die Settings auch nicht richtig dafür laden, das die Seite unter einer anderen Domain abegerufen wird (https://translate.google.com/translate?sl...). Das Dropdown-Menü für Sprachen fehlt ebenfalls, weil ich dafür auf die Addresse im Browser (window.location.href) verwende. - Komm gerade darauf, dass wir dass auch umgehen könnten, da die URL unabhängig von window.location.href erzeugt werden könnte. Dann hätte man auch auf Google Translate die anderen Sprachen angezeigt. - Sowei so gut und beabsichtigt.

Warum die Klasse "theme-default-content" nicht vorhanden ist, ist mir noch ein Rätsel. Sobald man die Stelle gefunden hat, dürfte es allerdings ein kleiner Fix sein. Hab jetzt die SSR Templates u.Ä. von vuepress danach durchforstet, aber auf die Schnelle nichts gefunden. Muss ich später machen.

**Comment by klues** [comment]
I implemented it in the [current release](https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2020-04-24-13.10%2F%2B0200).
