### ISSUE TITLE
Implement export to OBF (open board format)

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#47]
Follow-up issue for #41 

If someone would benefit from OBF export and not only import, please comment.

**Comment by msantos-87** [comment]
While I don't have any specific use for it at the moment, being able to have one board format accross various softwares is in my view a sensible part of the whole concept of open AAC, open source etc. So it would make sense to me if an open source software such as AsTeRICS would eventually offer OBF exports.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-06-03-14.05%2F%2B0200
