### ISSUE TITLE
quota limit exceeded on Firefox

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#50]
When trying to open the grid.asterics.eu page, the loading fails and I am getting the following error message:

![image](https://user-images.githubusercontent.com/4621810/81262296-db9b1500-903d-11ea-857e-7df92a05a4ad.png)

On Chrome it seems to work fine but maybe the initial settings (user to load) have not been the same.

**Comment by klues** [comment]
Strange, seems like too much indexedDB storage is consumed.

Could you provide this information:
1) In Firefox: `Menu -> Web Developer -> Web storage inspector -> indexedDB` -> how much Databases are there? (in my case 3: http://prntscr.com/scfi8m )
2) How big is this folder on your system: `C:\Users\<user>\AppData\Roaming\Mozilla\Firefox\Profiles\*.default\storage\default\https+++grid.asterics.eu` or on Linux it should be something like `~/.mozilla/firefox/*.default/storage/persistent/...`

**Comment by klues** [comment]
Also: How much free disk space do you have on your computer?

If enough, according to this page there should be up to 2GB for AsTeRICS Grid, which definitely should be enough:
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Storage_limits

**Comment by deinhofer** [comment]
> Strange, seems like too much indexedDB storage is consumed.
> 
> Could you provide this information:
> 
>     1. In Firefox: `Menu -> Web Developer -> Web storage inspector -> indexedDB` -> how much Databases are there? (in my case 3: http://prntscr.com/scfi8m )
> 
>     2. How big is this folder on your system: `C:\Users\<user>\AppData\Roaming\Mozilla\Firefox\Profiles\*.default\storage\default\https+++grid.asterics.eu` or on Linux it should be something like `~/.mozilla/firefox/*.default/storage/persistent/...`

![image](https://user-images.githubusercontent.com/4621810/81280045-3d687880-9058-11ea-806d-acd0229c1240.png)

```bash
mad@martin-T480:~/Downloads$ du -xh ~/.mozilla/firefox/*.default/
8,0K	/home/mad/.mozilla/firefox/iw5vy7sb.default/
```

**Comment by deinhofer** [comment]
![image](https://user-images.githubusercontent.com/4621810/81280683-21190b80-9059-11ea-9392-04492e20df8c.png)

**Comment by klues** [comment]
OK, 92% is a quite full disk, but nevertheless it should be enough to run AsTeRICS Grid, especially if you only have just a single user there.

Strange, I don't know what the problem could be.
As workaround you can try `Ctrl + Shift + Del` in Firefox and there tick `Clear Offline-Website data` http://prntscr.com/scj2ai
**Warning:** This deletes your AsTeRICS Grid configuration, however it should not be a problem, if `vkkj-ah` is an online user and you still now the password for it ;)

**Comment by deinhofer** [comment]
I did the ```Clear Offline Website``` and it resetted the grid. But when I wanted to open the default grid the problem appeared again:
![image](https://user-images.githubusercontent.com/4621810/81356578-ca034d00-90d1-11ea-96b5-ab322a01ba44.png)

**Comment by klues** [comment]
Ok, thanks for trying.

Which OS and version of Firefox do you use? Did you install any new updates or browser plugins recently?

**Comment by klues** [comment]
If this still happens please re-open.
