### ISSUE TITLE
Add possibility to change background color of grids

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#53]
Feedback by user "tuttleturtle" on [openAAC slack channel](https://join.slack.com/t/openaac/shared_invite/zt-6wakcmo3-AIP_OPv5LaZh_WdARFcBTw):
* not having the ability to change the background color is really limiting

**Comment by klues** [comment]
related: https://github.com/asterics/AsTeRICS-Grid/issues/53

**Comment by sabicalija** [comment]
Would be great if "dark-mode" was supported/detected too.

* https://css-tricks.com/dark-modes-with-css
* https://caniuse.com/?search=prefers-color-scheme

**Comment by klues** [comment]
Yes, thanks for the suggestion.
I'm closing this in favor of #28 and will copy your comment there.
