### ISSUE TITLE
Manage Grids View not up2date (after import?)

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#64]
## Problem

After importing a grid (see #63 ) the "Manage Grids" view is not up2date. The thumbnails are missing as described in #63, but also the grids are not shown as connected, although they are if you open the main grid and click on a subgrid. Opening the subgrid "Wohnzimmer" and changing back to "Manage Grids" did not show the grid of "Wohnzimmer" in the details view but "Schlafzimmer". It seems that "Wohnzimmer" is orphaned although it still can be opened from within the main grid.

## How to reproduce

Use the grid backup of #63

**Comment by klues** [comment]
The reason is that in this configuration the element "Wohnzimmer" actually navigates to grid "Schlafzimmer", see http://prntscr.com/uffxus
So it's a misconfiguration and not a bug.
