### ISSUE TITLE
After "Delete all grids", the main view can't be opened any more

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#66]
## Problem

Click on "Manage Grids / More / Delete all grids" and then go to "Main" (left menu)

See
![image](https://user-images.githubusercontent.com/4621810/86222986-43299880-bb87-11ea-8cb6-bdb6bf51579f.png)

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2020-09-11-11.36%2F%2B0200
