### ISSUE TITLE
Language of grid-controls and language of default grid

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#7]
On my Linux machine (English) the grid ui automatically adapts to English. Can this be overridden manually?

Is there a way to define a default grid per language? 
e.g. If the user has a locale setting for german, deliver a default grid in german, if he/she has a locale setting for english, deliver a default grid for english.

Does this make sense?

**Comment by deinhofer** [comment]
@klues is a default grid per language possible or existent at the moment?

**Comment by klues** [comment]
Currently the Grids from examples/default_[Language_code].grd are imported by default where the language code is the default language of the browser, e.g. "de" for German. If the correct .grd file is not found "default.grd" will be imported, which is currently an English grid.

**Comment by klues** [comment]
today for I've added the possibility to manually set the language by executing:
`setLanguage('en')` or
`setLanguage('de')`
in the javascript console. After a page refresh the language adapts. I needed this for fast switching for creation of screenshots in both languages for the manual.

Maybe this options should be available in the GUI at some time, but I don't think it's very important or needed at the moment.
For the moment I'll close this issue.

**Comment by deinhofer** [comment]
thanks, good idea.
What also works is to change the language in the browser preferences and reload the grid page.

**Comment by klues** [comment]
yes, of course, but it's very time consuming if you have to do it for every screenshot...
