### ISSUE TITLE
Integrate OpenHAB API

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#74]
Add new grid element actions for accessing actions provided by [openHAB REST API](http://demo.openhab.org:8080/doc/index.html).

**Comment by NotTheCaptain** [comment]
See #209

**Comment by rgabo74** [comment]
Hey, it is fun to have openHAB integration. I wanted to try this out, but failed on it.
- If I provide http openhab URL, the fetch of items fail with mixed content browser error
- My openhab does not have a domain, so I don't have https on openhab
- AsTeRICS Grid auto redirects to https
So I did not find the way to make this action work.

**Comment by NotTheCaptain** [comment]
Please refer to the [docs](https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/05_actions.md#openhab-action) for the openHAB action.

>If I provide http openhab URL, the fetch of items fail with mixed content browser error

You can enable mixed content for Asterics Grid (e.g. for Chrome and Firefox https://experienceleague.adobe.com/docs/target/using/experiences/vec/troubleshoot-composer/mixed-content.html?lang=en)

>My openhab does not have a domain, so I don't have https on openhab

You don't need a domain for https. By default, openHAB opens two Port, 8080 and 8443. You can use openHAB locally with both of them. You can also use this action with both ports (see [docs](https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/05_actions.md#accessing-openhab-via-httphttps)).
