### ISSUE TITLE
Add possibility to search for elements

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#77]
**User feedback:** it would be nice to have a global search function in order to quickly find existing elements and the place/grid where it is.

Possibliy it's best to implement it somewhere in the Manage Grids view, and do this while also working on https://github.com/asterics/AsTeRICS-Grid/issues/14

**Comment by klues** [comment]
Idea / user feedback:
Search for existing elements in current gridset, show all search results next to each other, actions (e.g. speech) can be directly triggered from clicking on elements in search results.

Below search results maybe also show results from opensymbols.org

**Comment by klues** [comment]
Also see discussion https://github.com/asterics/AsTeRICS-Grid/discussions/239

**Comment by jamjolu** [comment]
Hi Benjamin,

I like the search feature very much, but it is doing some odd things:
If (I am using Quick Say 20) I search for the string* fast *I see the paths
to both the adjective *fast* and 2 references to the word break*fast.*

If I click the symbol, I am taken to the element and grid where the string
is found. The element is flashing.
If I click the string at the end of the search path, I am being led by
flashing elements through the path to the destination element. But, that
does not happen. The flashing elements are not leading me correctly to the
destination elements - I tried a few common browsers. Am I mistaken?

The path shown in the search modal is always correct.

Could there be a choice of the Global Grid with and without the search
function?

Just some thoughts,
jl

**Comment by arasaac-dga** [comment]
Good morning, Benjamin. First of all, great job as always. Congrats!!!! We are going to reply to your questions and share the issues that we have found. 

**TO DO / OPEN FOR DISCUSSION:**

1) _"Currently there is no search button in manage grids and edit grid, only the Ctrl + F is possible. Do we need a button there Where? I would assume that "power users" will quickly adapt to Ctrl + F and don't need an additional button. If we need it, I think the only place to add it would be within the "More" button. We have to think in tablet users too where is impossible to use Ctr+F. So we need a search button al most in Manage Grids page (in edit mode is enough with Ctrl+F). We atttach you the poisition that we think is the best (addtionaly we have change the position of number of grids that we think is more suitable)"_

![search_button_position](https://github.com/asterics/AsTeRICS-Grid/assets/82500056/e3a44ce3-e736-4aaa-aa13-565614ef9c55)

You can add too in More menú but we think it is more accessible in the position we have suggested. 

2) _"I think we would need an additional pictogram for searching, in the same style as the others in the global grid, @arasaac-dga"_

We have made and upload one new pictogram here: https://arasaac.org/pictograms/es/39110/

3) _"New strings in crowdin should be translated, @arasaac-dga"_

Translated

4) "Should all default gridsets be updated to contain the new global grid?"

We don't think that you must add the new search button in Global Grid. We are more comfortable with the actual global grid. Search option is only for advanced users. So it will not be commonly used by users and they have the upper button in the header to access this option. On the other hand Global Grid has many buttons and adds one more supposed less space for accumulated phrase. So, please come back to the old global grid version (of course with the new features for home and come back buttons).

**ISSUES:**

In general the search option works as expected in most of the searches but we have found some issues. We attach some videos to see them:

1) In Edit Cell mode, when you press Ctrl+F the search dialog window is placed behind the Edit Cell Window

[https://app.box.com/s/r1ml6alkqbo918tm2g40kzjf5zok4wim](https://app.box.com/s/r1ml6alkqbo918tm2g40kzjf5zok4wim)

2) Using our ARASAAC Predefined Communicator we have found issues searching elements placed in Core 50 grid when you use the option to follow the route (with direct access there is no problem). As you can see always go to the same pictogram and not the selected one (goes to "Se acabo"). 

[https://app.box.com/s/vauckqff5ahgr71naeivs69do65o7s0j](https://app.box.com/s/vauckqff5ahgr71naeivs69do65o7s0j)[https://app.box.com/s/wnso4z438hf9gfz30zxjp01wpr0n6jkd](https://app.box.com/s/wnso4z438hf9gfz30zxjp01wpr0n6jkd)[https://app.box.com/s/wahpxuj1kp22hygxp1a41tz6bsbnscdv](https://app.box.com/s/wahpxuj1kp22hygxp1a41tz6bsbnscdv)[https://app.box.com/s/f6qsof8qmfyu3otbdimlixv5ylgbj07o](https://app.box.com/s/f6qsof8qmfyu3otbdimlixv5ylgbj07o)[https://app.box.com/s/leejqr392stn39e23h17pd6ifnbo5wjq](https://app.box.com/s/leejqr392stn39e23h17pd6ifnbo5wjq)[https://app.box.com/s/rbksx7l38lqqp476uimx2l058borhcsj](https://app.box.com/s/rbksx7l38lqqp476uimx2l058borhcsj)

As you can see there are errors with the initial cell of the route that blinks continuously when you come back to the initial grid. 

The new options in "Navigate to" action work as expected. No problems detected.

**Comment by jamjolu** [comment]
As an alternative to adding the search feature to the Global Grid, how
about including search as an available action for an element. That way
someone who wants the search feature on their Global Grid can add it
whenever they want.
jl

**Comment by arasaac-dga** [comment]
@jamjolu Benjamin has added as sub-action inside "Navigation to other grid" action. Look the capture that Bejamin share with us. In "Navigation type" selecting "Open search dialog" you can assign this action to any cell you wish (with or without custom text). 

![290552106-d08d5705-82fe-45cf-8cf4-35f50ea6bf2b](https://github.com/asterics/AsTeRICS-Grid/assets/82500056/de742b26-ad40-4c10-9958-171fe244a794)

**Comment by klues** [comment]
I've just released a new version to https://grid.asterics.eu/latest/

> The flashing elements are not leading me correctly to the destination elements

Thanks for finding this bug - it should be fixed.

> You can add too in More menú but we think it is more accessible in the position we have suggested.

Do you think many people will use the button or at all the search function within "Manage grids"? Or should we just provide the keyboard shortcut as now for power users? What about "edit grid view"?

> So, please come back to the old global grid version (of course with the new features for home and come back buttons).

OK, I've removed the search button from the default global grid again.

> In Edit Cell mode, when you press Ctrl+F the search dialog window is placed behind the Edit Cell Window

Now it's in the foreground - however I think it's a rare case that someone goes to the search dialog while editing an element.

> Using our ARASAAC Predefined Communicator we have found issues searching elements placed in Core 50 grid when you use the option to follow the route (with direct access there is no problem). 

I think it was the same issue also @jamjolu reported - should be resolved, please test.

Fun fact: @jamjolu 's Quick Say 20 has a total of `28038` possible paths to all other grids starting from the home grid, I've now further optimized performance, so that searches in this complex network now take below 500ms.

**Comment by msantos-87** [comment]
Hi Benjamin

I just tested after the latest update:
Safari 17.0, Macbook as well as Samsung Android. The leading-through-the-full-path is not working, it skips directly to the page, for both, the fullscreen search and the not-fullscreen search option.
Safari, iPad 16.7. The fullscreen search exits fullscreen once you click on the search button. The leading-through-the-full-path is not working either.
I think this was working before the latest update.

**Comment by klues** [comment]
Strange, please describe step by step what you're doing. If I test:
1. Add new user and import `AsTeRICS Grid default`
2. Search for `german`, I see this result:
![image](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/d3e1d86f-2775-4ae4-9ee6-c39ccde375f8)
3. After clicking on the path (red marked) it leads me step-by-step to the correct element. Clicking on the image directly shows the element.

Tested in Chrome and Firefox on Win10 and Safari on iPad Pro.

**Comment by klues** [comment]
I've tested again in Firefox, it seems like it wasn't the latest version running there. Now everything works in all browsers for me, so I cannot reproduce the issue.

**Comment by msantos-87** [comment]
After clearing cache and re-importing everthing the step-by-step-function now works again on the Macbook, Android and iPad :) The full screen issue on the iPad remains, though: For Safari and Chrome it exits full screen when I want to search. For Firefox the full screen isn't working at all. All apps are updated.

**Comment by arasaac-dga** [comment]
> I've just released a new version to https://grid.asterics.eu/latest/
> 
> > The flashing elements are not leading me correctly to the destination elements
> 
> Thanks for finding this bug - it should be fixed.

Yes, it's fixed 

> 
> > You can add too in More menú but we think it is more accessible in the position we have suggested.
> 
> Do you think many people will use the button or at all the search function within "Manage grids"? Or should we just provide the keyboard shortcut as now for power users? What about "edit grid view"?

We are discussing again and we agree that perhaps the Search button is not needed in Manage Grid page. Thinking in people that edit boards from a tablet (with no keyboard) perhaps it would be more suitable in More menu as you initialy proposed (of Edit Grid page only, not in more menu of Manage Grids).

> 
> > So, please come back to the old global grid version (of course with the new features for home and come back buttons).
> 
> OK, I've removed the search button from the default global grid again.

Thanks

> 
> > In Edit Cell mode, when you press Ctrl+F the search dialog window is placed behind the Edit Cell Window
> 
> Now it's in the foreground - however I think it's a rare case that someone goes to the search dialog while editing an element.

Yes it's a rare cae but always is better that is in the correct position.

> 
> > Using our ARASAAC Predefined Communicator we have found issues searching elements placed in Core 50 grid when you use the option to follow the route (with direct access there is no problem).
> 
> I think it was the same issue also @jamjolu reported - should be resolved, please test.

Yes, it works fine now. 

> 
> Fun fact: @jamjolu 's Quick Say 20 has a total of `28038` possible paths to all other grids starting from the home grid, I've further optimized performance, so that searches in this complex network now take below 500ms.

**Comment by jamjolu** [comment]
Thanks, it works as expected.
Tested in Chrome, Firefox, Edge.
jl

**Comment by klues** [comment]
> The full screen issue on the iPad remains, though: For Safari and Chrome it exits full screen when I want to search. 

Thanks for the hint. I've tried it and could reproduce it. I assume that maybe Safari automatically stops fullscreen at showing the keyboard?! However if you "install" the app (add it to home screen and start it from there), for me staying in fullscreen and searching works. However if there's anything left to be done regarding this, please just open a new issue.

> Thinking in people that edit boards from a tablet (with no keyboard) perhaps it would be more suitable in More menu as you initialy proposed (of Edit Grid page only, not in more menu of Manage Grids).

Ok, I'll add it there and then release everything to main version.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-01-03-12.25%2F%2B0100
