### ISSUE TITLE
Opening grid.asterics.eu not working offline

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#8]
There are situations where the user is offline (not connected to the Internet).

In such a case, the URL https://grid.asterics.eu can't be opened, as the browser wants to lookup the domain name and load the contents of the page.

## Solution
Implement Progressive Web App functionality (PWA).
PWAs support caching of a web application. In case of an offline device, the PWA worker returns the cached version of the web page.
See this tutorial: https://developers.google.com/web/progressive-web-apps/

Or the Asterics homepage: https://www.asterics.eu

**Comment by klues** [comment]
AsTeRICS Grid is already usable offline. However https://grid.asterics.eu redirects to https://grid.asterics.eu/app/ and this redirection page was not cached. I've now implemented it, should work now.

**Comment by deinhofer** [comment]
great!! could successfully test it on Chrome! :-)
On Firefox, I had this issue #9 

How did you implement the offline support? Maybe nevertheless it makes sense to support PWA one day, as it makes a more native user experience, and on smartphones and tablets the web app can also be installed on the device.

**Comment by klues** [comment]
Currently I'm using Appcache for offline support. It's the easier to use predecessor of ServiceWorkers. It's kind of a problem, that recent browsers are all deprecating support of Appcache and encouraging to use ServiceWorkers while not all browsers are supporting ServiceWorkers (mainly IE):
1) https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache
2) https://caniuse.com/#feat=serviceworkers

At some point probably I'll switch to ServiceWorkers, but while Appcache is working on all browsers and ServiceWorkers aren't, I don't want to drop the currently working IE support by switching to ServiceWorkers.

However thanks for your hint regarding progressive webapps, I've just included a webmanifest to AsTeRICS Grid which now makes it "installable" on a smartphone. In Chrome just open grid.asterics.eu and then in the Chrome menu select "add to homescreen" -> results in an app icon on the homescreen and when opening it, it really looks like a native app 👍 😃 

![signal-attachment-2019-07-24-095824](https://user-images.githubusercontent.com/2537025/61776205-db0cf700-adfa-11e9-9528-96f5be47a6b7.jpeg)

**Comment by klues** [comment]
just changed the URLs:
1. https://grid.asterics.eu/ now is the default URL
1. https://grid.asterics.eu/app/ now redirects to https://grid.asterics.eu/

This is a cleaner solution as before since I don't have to cache the `index.html` that is redirecting to the main URL with a separate `manifest.appcache`.
Please verify that everything is still working.
