### ISSUE TITLE
Impossible to leave fullscreen mode on touchscreen desktop without keyboard

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#81]
Currently there are the following possibilities to leave fullscreen mode:
* Press `Esc` on keyboard
* Swipe down from top on mobile platform

There should also be a possibility to leave fullscreen without keyboard on desktop.

**Comment by ms-mialingvo** [comment]
Leave fullscreen through an element/button that does that action. No swiping, no esc.

**Comment by klues** [comment]
I've added the possibility to enter/leave fullscreen via the new `System action`.
Also released to "latest", test it with the configuration from [this comment](https://github.com/asterics/AsTeRICS-Grid/issues/420#issuecomment-2360636286), where I've also added elements to enter/leave fullscreen to the global grid.

**Comment by ms-mialingvo** [comment]
Awesome, it works, thank you!

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2024-10-10-09.52%2F%2B0200
