### ISSUE TITLE
Tutorial Videos can not be played from translated help pages

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/AsTeRICS-Grid#82]
If the grid language is differnt from english (and the help pages are thus automatically translated),
the links to the youtube tutorial videos do not work,

see example:

![ScreenHunter 19](https://user-images.githubusercontent.com/328325/108637038-2aa91e00-7489-11eb-952b-7d4607be01b1.png)

**Comment by klues** [comment]
Very strange, I don't know what's happening here. Google Translate somehow changes the video links to something like this: https://translate.google.com/website?sl=en&tl=de&u=https://www.youtube.com/watch?v%3D5ffLB4a9APc%26list%3DPL0UXHkT03dGrIHldlEKR0ZWfNMkShuTNz%26index%3D2%26t%3D0s
which then results in this strange dutch modal which also doesn't work after clicking "Nee, bedankt"...

The only thing I/we can do is to remove Google Translate and turn back to showing only the original english help. What do you and @deinhofer think?

**Comment by klues** [comment]
The auto-translated version of the manual isn't used anymore, so this issue isn't existing anymore.
