### ISSUE TITLE
Translated help: YouTube links don't work

### ISSUE THREAD

**Issue by klues** [asterics/AsTeRICS-Grid#87]
Reproduce:
1. Open "Help" in AsTeRICS Grid in a German browser
2. Auto-Translated version opens: https://translate.google.com/translate?sl=en&tl=de&u=https://www.asterics.eu/manuals/asterics-grid/02_navigation.html#main-view
3. Click on a linked YouTube Video
4. This Dutch modal opens: http://prntscr.com/110kpzf - after clicking "nee, bedankt" there is this error: http://prntscr.com/110kqiu

Solution: remove auto-translation from Google Translate?!

**Comment by deinhofer** [comment]
The strange thing is that external links like links from youtube are wrapped with google translate as well. Do you know if this can be prevented? Because there is no need to translate the youtube link.
@sabicalija any ideas?

**Comment by sabicalija** [comment]
Hi, sorry, I didn't see this message earlier.

What I don't understand is `Pt. 2.` in @klues list. Why does the auto-translated version open, anyway?
Is this a feature of AsTeRICS-Grid?

@deinhofer not only youtube links are wrapped within google translate but all links. I wasn't aware of this "feature" before.

**Comment by klues** [comment]
> What I don't understand is `Pt. 2.` in @klues list. Why does the auto-translated version open, anyway?
> Is this a feature of AsTeRICS-Grid?

We had discussed this some day (at least with Martin) and then we decided to use the auto-tranlsated version of Google Translate. But I'm not really convinced by the translation anyway, so maybe I'll revert it to the original version one day.

**Comment by klues** [comment]
The auto-translated version isn't used anymore, so this issue can be closed.
