### ISSUE TITLE
Checkbox "Aktives Element vorlesen" should be independent of Hovering activation

### ISSUE THREAD

**Issue by deinhofer** [asterics/AsTeRICS-Grid#97]
When activating the checkbox for "Hovering" under "Mouse/Touch input", a checkbox appears which let's the user activate the reading out of the active element. The reading out also works, if hovering is deactivated (which is good), but you don't see the current state of the checkbox because it appears/disappears with the hovering state.

## Hovering active

![image](https://user-images.githubusercontent.com/4621810/123818607-6baeb480-d8f9-11eb-86b6-549a976cf55e.png)

## Hovering inactive, Read out active

![image](https://user-images.githubusercontent.com/4621810/123818776-8e40cd80-d8f9-11eb-9377-d87ddc530468.png)

**Comment by klues** [comment]
I've just tested it, for me there is no reading if hovering deactivated. Have you tried it on desktop or touch device?
I think it's the same property that is also editable in "Sequential input", so if sequential input is active, the current element also should be read out loud. I think it would also make sense for "Direction input".

In which case you want reading out the current element, but no hovering?

**Comment by deinhofer** [comment]
Ah, you are right. I did not see that option in "sequential input" and it was activated on my machine.

I need the reading out loud for sequential input, so it's fine now. Yes, I agree, for Direction Input it would make sense as well.

**Comment by klues** [comment]
I've added advanced acoustic feedback options, see this comment: https://github.com/asterics/AsTeRICS-Grid/issues/170#issuecomment-1289211237
You can test them at https://grid.asterics.eu/latest/

**Comment by klues** [comment]
I think this should be fixed, if not feel free to reopen.
